### ISSUE TITLE
session not fetched, call fetch_session

### ISSUE THREAD

**Issue by echojaybird** [smpallen99/coherence#1]
Getting an error when trying to navigate to any of the Coherence routes.

Phoenix 1.2, Elixir 1.3, Ecto 2.0.1

Steps I took.

1. mix phoenix.new divi
2. mix ecto.gen.migration initial_schema (added a "users" table with email/name fields)
3. mix ecto.migrate
4. followed installation instructions
5. mix coherence.install --full-invitable --controllers
6. mix ecto.migrate

router.ex
```
defmodule Divi.Router do
  use Divi.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Database, db_model: Divi.User
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :public do
    plug :accepts, ["html"]
    plug Coherence.Authentication.Database, db_model: Divi.User, login: false
  end

  scope "/", Divi do
    pipe_through :public
    coherence_routes :public
  end

  scope "/", Divi do
    pipe_through :browser
    coherence_routes :private
    get "/", PageController, :index
  end
end
```

user.ex
```
defmodule Divi.User do
  use Divi.Web, :model
  use Coherence.Schema

  schema "users" do
    field :email, :string
    field :name, :string
    coherence_schema
    timestamps
  end

  @required_fields ~w(name email)
  @optional_fields ~w() ++ coherence_fields

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:email)
    |> validate_coherence(params)
  end
end
```

Navigating to any of the routes generated by Coherence gives me `session not fetched, call fetch_session/2` error.

**Comment by smpallen99** [comment]
@echojaybird Wow, that was quick. I have not even announced the project yet :). I’ll give is a try on current master, then try it on my latest local changes I have not yet pushed. Project is still in active dev. I’ve been manually acceptance testing on a local test project. I have not yet tired integrating it with any of my production project yet. So, user beware :)

Thanks for raising the issue!

Steve

**Comment by echojaybird** [comment]
No problem!

I've been obsessively keeping an eye out for a better out-of-the-box authentication solution for Phoenix. Coherence is one more notch on my belt :)

Looking forward to the package.

**Comment by smpallen99** [comment]
@echojaybird Just tested a new project and it worked fine. I see your issue though. 

You need to add the additional plugs to your :public pipeline.

These changes should get you running:

```elixir
  pipeline :public do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Database, db_model: Divi.User, login: false
  end
```

I'll update the installer instructions and documentation to reflect this. 

Let me know if that works. Thanks again for raising the issue!!

Steve

**Comment by echojaybird** [comment]
@smpallen99 Fantastic, that works! Awesome package. Will continue playing with it.

**Comment by smpallen99** [comment]
@echojaybird Would love your feedback.  I’m testing some updates now and hope to push soon. Biggest update is new rememberable option.
