### ISSUE TITLE
[SOLVED] Logout link?

### ISSUE THREAD

**Issue by alzearafat** [smpallen99/coherence#100]
Hi there!

I cannot find logout/signout tutorial on readme. I tried this link : `/sessions/delete`, but I'm getting : 
```
no route found for GET /sessions/delete (Ideabox.Router)
```

I also try something like this : 
```
<%= link("signout", to: coherence_path(@helpers, :session_path, conn, :delete, current_user), method: :delete, class: signout_class) %>
```

But it gives me another error, compiling error : 
```
== Compilation error on file web/views/idea_view.ex ==
** (CompileError) web/templates/idea/index.html.eex:21: undefined function coherence_path/5
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I'm pretty sure I already following the readme.

In rails, I can do something like this : 
```
<%= link_to("Logout", destroy_user_session_path, :method => 'delete', data: {confirm: "Are you sure?"}, class: "ideabox-btn") %>
```

Thank you in advance for any help you can provide :)
Regards

**Comment by kimquy** [comment]
@alzearafat You can try something like

```elixir
YOURPROJECT.Coherence.ViewHelpers.signout_link(conn)
```

**Comment by alzearafat** [comment]
@kimquy thank you for your response

Sadly, still not working :(

```
Compiling 1 file (.ex)

== Compilation error on file web/views/idea_view.ex ==
** (CompileError) web/templates/idea/index.html.eex:21: undefined function conn/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Here's my code : 

```
                        <ul class="nav navbar-nav navbar-right">
                            <%= if @current_user do %>
                            <li style="margin-right: 10px;"><%= Ideabox.Coherence.ViewHelpers.signout_link(conn, class: "ideabox-btn") %></li>
                            <% else %>
                            <li style="margin-right: 10px;"><%= Ideabox.Coherence.ViewHelpers.coherence_links(conn, class: "ideabox-btn") %></li>
                            <% end %>
                            <li style="margin-right: 10px;"><%= link("New Idea", to: "/sessions/delete/", class: "ideabox-btn") %></li>
                        </ul>
```

Thank you

**Comment by kimquy** [comment]
@alzearafat Can you try this

```elixir
Ideabox.Coherence.ViewHelpers.coherence_links(@conn, "Sign Out", "ideabox-btn")
```

**Comment by alzearafat** [comment]
@kimquy thank you again, but still no luck :( 

Here's the error : 

![alt text](http://i63.tinypic.com/9r1rh5.png "error")

Did I miss somethong on the readme? The installation process maybe? But I'm pretty sure I already following the readme... :/ 

Thanks

**Comment by kimquy** [comment]
@alzearafat The signout link I suggested seem work right ?

FYI: the way you use the `coherence_links` seem not right. Can you try the below

```elixir
Ideabox.Coherence.ViewHelpers.coherence_links(@conn, :new_session)
```

NOTE: you need to use `@conn` in the view, not `conn`

**Comment by alzearafat** [comment]
@kimquy Thank you... No it's still doesnt work :(

The `Ideabox.Coherence.ViewHelpers.coherence_links(@conn, :new_session)` is working thou, but instead of produce one single link (e.g Sign Out), it generated 2 links instead... 

What I'm trying to achive is pretty simple, just like this : 
![alt text](http://i68.tinypic.com/2565ocp.png "error")

And about the NOTE, do you mean in view? Or template? Because They seems different on Phoenix AFAIK :/

Thank you again

**Comment by kimquy** [comment]
Yeah. It's working for me. Here is how those view helpers implemented. Not sure you got chance to look at them ?

https://github.com/smpallen99/coherence/blob/master/web/views/view_helpers.ex

Hope it might help!

**Comment by alzearafat** [comment]
@kimquy Yes it does work! :D 

Thank you. Here is what I use : `<%= Ideabox.Coherence.ViewHelpers.coherence_links(@conn, :layout) %>`

But when I click sign out, it's lead me to another issue : 

```
function Ideabox.Coherence.SessionController.init/1 is undefined (module Ideabox.Coherence.SessionController is not available)
```

**Comment by jaimeiniesta** [comment]
I also have this issue. In Coherence 0.2 this worked:

```elixir
<%= link "Log out", to: session_path(@conn, :delete, :nothing), method: :delete %>
```

But now I'm upgrading to Coherence 0.3 and this fails with:

```
No helper clause for Rocket.Router.Helpers.session_path/3 defined for action :delete.
The following session_path actions are defined under your router:

  * :create
  * :new
```

These are the Coherence routes available, the one for :delete is missing:

```
➔ mix phoenix.routes
               session_path  GET     /sessions/new                       Coherence.SessionController :new
               session_path  POST    /sessions                           Coherence.SessionController :create
          registration_path  GET     /registrations/new                  Coherence.RegistrationController :new
          registration_path  POST    /registrations                      Coherence.RegistrationController :create
              password_path  GET     /passwords/:id/edit                 Coherence.PasswordController :edit
              password_path  GET     /passwords/new                      Coherence.PasswordController :new
              password_path  POST    /passwords                          Coherence.PasswordController :create
              password_path  PATCH   /passwords/:id                      Coherence.PasswordController :update
                             PUT     /passwords/:id                      Coherence.PasswordController :update
          confirmation_path  GET     /confirmations/:id/edit             Coherence.ConfirmationController :edit
          confirmation_path  GET     /confirmations/new                  Coherence.ConfirmationController :new
          confirmation_path  POST    /confirmations                      Coherence.ConfirmationController :create
                unlock_path  GET     /unlocks/:id/edit                   Coherence.UnlockController :edit
                unlock_path  GET     /unlocks/new                        Coherence.UnlockController :new
                unlock_path  POST    /unlocks                            Coherence.UnlockController :create
```

...so I must be doing something wrong :)

**Comment by jaimeiniesta** [comment]
Solved, I had to add the `coherence_routes :protected` part to my routes.

**Comment by jaimeiniesta** [comment]
In my case, that part in the router was:

```elixir
scope "/" do
  pipe_through :browser
  coherence_routes
  coherence_routes :protected
end
```

Because in my project I enforce require user login at the controllers, not at the router.

Maybe a `coherence_routes :all` option would be shorter?

**Comment by alzearafat** [comment]
Coherence is great!

But a bit lack of template documentation. I'm having a hard time, trying to implement individual/single link on my template... Yes there's example project, but as someone who's not from ruby/rails background, I find it's quite difficult to understand  :)

Thanks anyway!

**Comment by smpallen99** [comment]
@alzearafat Is this what you ended up for disabling he registration link?
`coherence_links(@conn, :layout, register: false)`

I can add a statement in the docs to be explicate for disabling links and add the above example.

If you provide some more details on what "template documentation" you feel is lacking, I'll try to improve. Of course, PRs are always welcome too.

Thanks for you input,
Steve
