### ISSUE TITLE
Why is the password needed to unlock an account?

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#105]
I think that a typical scenario when an account is unlocked due to too many failed logins is that it's the real user that has forgotten her password, so her account is locked.

In that case, when she visits `unlocks/new` she needs to enter the password to have an unlock token sent by email - but as she doesn't remember the password, she must first reset the password and after that, request an unlock token.

I think it would be easier to not request the password to generate an unlock token, and make it only send the email in case the account is really locked.

But maybe I'm missing something and there's a good reason to request the password here.

**Comment by smpallen99** [comment]
The lock timeout is pretty short (default 5 minutes) and is intended to deter against brute force attempts. I don't see an issue with the extra security.

**Comment by StephaneRob** [comment]
Hi @smpallen99, might you be interested by a PR offering an option to use a devise like flow to unlock an account, ex: `{:direct_unlock, false}`, If `true` the email with unlock token is sent right when the account is locked.
