### ISSUE TITLE
Security: Better session handling

### ISSUE THREAD

**Issue by dsignr** [smpallen99/coherence#108]
Hi,
First of all, thank you for the wonderful library. Coming from a Rails background, of all the Elixir libraries I've tried, this one was the simplest and least complicated to use. So, thank you for that!

There is a strange bug (or is this expected behaviour?) I noticed while testing - 

1) Start with an empty Phoenix setup. Install coherence. Let's assume there is a protected resource called "Downloads".
2) User A logs in into the "Downloads" section.
3) Clean up the database, delete all tables. 
4) Re-run all migrations.
5) Reload the "Downloads" section on your browser. User A is still logged in!

**Question:** Shouldn't the user be logged out and asked to re-login upon clearing and migrating the database? I know that Devise does this. 

Thoughts?

**Comment by smpallen99** [comment]
First, thanks for the great feedback!!

I presume you did not stop the phoenix server while you dropped and recreated the database. If your have not enabled the remember me option at login (presuming you even installed the option), then what you have observed is exactly how its designed.
During login, a UUID is created. Your user resource is stored in an Elixir Agent with the UUID as the key. The UUID key is stored in your session. On subsequent visits, the UUID key is used to fetch current_user from the Agent creds store and saved in conn.assigns. So, the only database access is when you originally login.

The downside of this approach is that if you stop the server, you loose the credential store, requiring everyone to login again.

**Comment by dsignr** [comment]
Ah, that makes sense! Thank you for your great explanation.
