### ISSUE TITLE
Custom Controllers misleading

### ISSUE THREAD

**Issue by Troush** [smpallen99/coherence#11]
Hey! Thank you for grate library!
As I see coherence as "Plug&Play" solution for authentication generators need to create controllers automatically, and have options to not include it. 
So not adding it by default is a bit misleading, because controllers is a core functionality of library 
https://github.com/smpallen99/coherence#custom-controllers

What to do think? I can do PR to change this behavior

**Comment by smpallen99** [comment]
So far, I have not had the need to modify controllers in my projects that used coherence. That is why I default to not installing then. But that is just me.  

Let's give this a couple days to see what others think. 

Everyone, please vote.

**Comment by Troush** [comment]
@smpallen99 currently i have error that SessionController is not found if not generating it.
Maybe this is a bug?

**Comment by smpallen99** [comment]
Can you provide the mix task you ran. ie. mix coherence.install ….

**Comment by smpallen99** [comment]
@Troush Please provide the coherence section of your config/config.exs file as well as the full coherence.install mix task you ran. Thanks.

**Comment by Troush** [comment]
First one was:
`mix coherence.install --full-invitable --full-confirmable --rememberable`
And when it was showing error that SessionController is undefined I add `--controllers`

**Comment by smpallen99** [comment]
@Troush I suspect I know why your getting the session controller error. Did you have your public route namespaced? If you define it like:

```
  scope "/" do
    pipe_through :public
    coherence_routes :public
  end

  scope "/" do
    pipe_through :browser
    coherence_routes :private
  end
```
It should find the built in controllers. 

Note the `scope "/" do` and not `scope "/", MyProject do`

The conference_routes generate a route to Coherence.xxxController and should work out of the box. If you generate controllers, they they are called `MyProject.Coherence.xxxController`. In which case the following will work:

```
  scope "/", MyProject do
    pipe_through :browser
    coherence_routes :private
  end
```

**Comment by Troush** [comment]
Ah, okay.
This looks like my error, but this need to be explained my explicit in docs.
I will close this issue then
