### ISSUE TITLE
Suggest to configure layouts via put_layout and put_new_layout

### ISSUE THREAD

**Issue by josevalim** [smpallen99/coherence#110]
After checking out the README, it seems the most complex part to configure is the coherence layout. So while I haven't verified this, I would like to point out that Phoenix ships with two nifty functions called `put_layout` and `put_new_layout` that allows you to pick which layout to use when rendering. For example:

1. If you assume you have a coherence pipeline in your routers that is used by all coherence routes, you can then tell developers to do this:

    pipeline :coherence do
      plug :put_layout, {MyApp.Layout, :app}
    end

  The above will use the same layout as for everything else.

2. Another option is to pass the layout option on `coherence_routes`, which automatically sets the layout

3. Or finally they may set it explicitly in their coherence controllers (if they have access to it)

Hopefully those suggestions can help make layout configuration a bit more straight-forward. :)

**Comment by smpallen99** [comment]
Thanks for the suggestion José. I'll update the readme file.
