### ISSUE TITLE
Race condition in rememberable

### ISSUE THREAD

**Issue by manukall** [smpallen99/coherence#112]
I think there is a race condition in Rememberable:

In my app I'm loading some resources via ajax after the initial page load, so a few requests might be triggered quickly after each other. 
Now when I logged in and checked 'remember me', after restarting the server, refreshing my browser will lead to `[warn] Invalid token. Potential Fraud.` in my logs and I'll be logged out.

**Comment by smpallen99** [comment]
Can you provide your router.ex file and identify the ajax routes. Thanks

**Comment by manukall** [comment]
i've set up a little example project: https://github.com/manukall/coherence_ajax_test

`/private` is the protected route. it also fires two ajax requests to another protected router.
when you go there after signing in and restart the server, the above behavior will be triggered.

**Comment by smpallen99** [comment]
I can see the possibility of a concurrency issue. There is a database read, calculation of a new seq number, and database write in the session plug. I need to serialize this code by adding a server and passing messages to the server to process sequentially.

**Comment by manukall** [comment]
@smpallen99 thanks for looking into it. i'm afraid this didn't fix the problem though. i've updated coherence in the test project and the issue is still there. 

what i think happens is:
- the second ajax request starts before the first one returns. 
- when the second one arrives at the server, it is still using the older cookies but it's rememberable token is already deleted from the database.

i've looked into how devise handles this, and i think they only delete the rememberable token from the db after logging out.
maybe this is the way to go, as i think having some ajax request to a projected route is a valid and also not too rare use case.

**Comment by smpallen99** [comment]
@manukall Thanks for the quick feedback. I did some research into the security aspects of "remember me" which my implementation is based on. As such, a new sequence number is generated for each new request. This is done to catch the case of an unauthorized party stealing someone's session and reusing it to gain access to the site. 

To resolve your issue, we have a couple options:

1. Don't use rememberable
1. Implement an insure version of rememberable
1. Disable the serial number check for ajax requests
1. Modify your application's design to serialize the ajax requests so request 1 completes before ajax request 2 is attempted

What are your thoughts?
Steve

**Comment by manukall** [comment]
@smpallen99 thanks for taking the time to help me with this.

i could not really find a convincing argument for the sequence number. i found https://stackoverflow.com/questions/244882/what-is-the-best-way-to-implement-remember-me-for-a-website, but even there people are arguing about whether it's a good idea. if an attacker get access to my session, he is essentially indistinguishable from me, so how does this prevent him taking over my account? it's basically a race of who makes the first request then.

of the options you presented, (if i want to provide the rememberable functionality), i think option 3 would be the only feasible. option 4 would be pretty bad in single page apps, where there could be a lot of requests to load resources. serializing all of them seems both too complicated and bad for performance.

i would argue however, that what devise does here is a pretty good compromise for all requests. if i understand correctly, the current approach would log me out on other devices once remember me kicks in on one. so if i'm using a site on both my laptop and my smartphone, remember me would only work on one of them at any time. plus i respect the devise people (plataformatec, hey jose ;-)) a lot and trust they did their due diligence.

**Comment by smpallen99** [comment]
@manukall Yes, that is the thread I based the design. Your right, the presumption is that the "real" user will access the site before the hijacker. However, even if the "real" user accesses the site after the hijacker, all uses will be logged out at that time, disabling the long term access to the site. 

As for multiple devices logged in to the same account, this is not an issue. Each new rememberable login creates a new rememberable_token which does not change for the duration of the session. Only the sequence number is updated on each new request. 

I see your point for single page apps.

I'll take a look at an ajax solution, perhaps this evening. 

Thanks for the feedback,
Steve

**Comment by manukall** [comment]
@smpallen99 thanks again! really appreciate you taking this seriously.

you're right about the multiple devices issue. i misunderstood this.

another issue i noticed today is multiple browser tabs, though. when phoenix triggers auto reload, the same  race condition occurs. this is not so serious, though, as i don't really see what would trigger several tabs to reload at the same time in production.

please let me know what i can do to help with this. thanks again for your time.

**Comment by smpallen99** [comment]
What I'm thinking about trying is to generate a new sequence number for each ajax request, but not validate the existing one for AJAX requests. However, this won't handle the case of multiple browser taps since they would all share the same session and be regular http requests.

I need to think about this a bit more.

**Comment by smpallen99** [comment]
@manukall Give the ajax-rememberable-support branch a try. I tested it with your sample project. Thanks for that...

Pretty simple change. If its an ajax request, I don't update the sequence number. However, I still validate it. Therefore, all ajax requests will use the rememberable token and seq_no of the last http request. I think this should be pretty secure. If someone gets your session, they will be able to access the site until you do a request to the site, either a http or ajax request. 

The only negative security implications I can see is that ajax page requests don't increment the seq_no, so it won't invalidate the stolen session.  So in that aspect, its a little less secure, especially for single page apps.

Let me know what you think?

As I think about this more, I may the ability to enable/disable this ajax feature through configuration.

**Comment by manukall** [comment]
@smpallen99  i tried the ajax-rememberable branch and it looks good. thanks! i don't think the live reload thing really is an issue, so i'm quite happy :smile:

**Comment by smpallen99** [comment]
@manukall I've merged the branch into master. I also added `async_rememberable?` to the Coherence configuration. The default is false (more secure), so you will need to enable it your project's config.
