### ISSUE TITLE
A view module was not specified, set one with put_view/2

### ISSUE THREAD

**Issue by mcade** [smpallen99/coherence#115]
Whenever I navigate to a protected route while not being signed in I get the error `A view module was not specified, set one with put_view/2`
and the following snippet is highlighted:
```
  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end
```

How am I to redirect a non-logged in user when they try to visit a protected route?

**Comment by smpallen99** [comment]
login_callback now adds layout and configured/default layout.
