### ISSUE TITLE
User logged out after server restart

### ISSUE THREAD

**Issue by leishman** [smpallen99/coherence#117]
Hello, my user is getting logged out every time I kill and restart the server and I don't know why. My impression was that all authentication state is stored in the cookie and a server restart should not kill user sessions. Is this assumption incorrect?

I'm not sure where in the coherence code the authentication is failing and I can spend more time digging there if needed. I just thought I might be missing something easy that others have come across.

Thanks.

**Comment by smpallen99** [comment]
The only thing stored in the cookie is a token. This token is stored in a task which goes away when u restart. 

Use rememberable or you can backend the credential store in ur database to survive a restart

**Comment by leishman** [comment]
Ah ok I see. I was assuming it acted like Rails. Is there any documentation for using a DB-based session store?

**Comment by smpallen99** [comment]
@leishman Take a look at this new wiki entry https://github.com/smpallen99/coherence/wiki/Session-token-Ecto-Persistance

**Comment by leishman** [comment]
Wow thanks so much! Perfect.

**Comment by leishman** [comment]
I love this project and am very happy I discovered it. Great job. There are a few things I have found a bit confusing so far that I will list here. Once I get more comfortable with things I'd be happy to help contribute documentation and/or code to help make it even easier to get started:

- How HTTP authentication is actually being performed. It's not immediately obvious what cryptography and protocol is being used for authentication of token/info in cookie
- How to use Coherence to authenticate socket connections/channels

I'm pretty new to Phoenix/Elixir as well so some things may not be as obvious to me as those with more familiarity with the ecosystem.

Thanks again for making this library. We need this "Devise for Phoenix" really badly I think!!

**Comment by smpallen99** [comment]
@leishman Thanks for the feedback!! 

The Session plug is pretty simple. First, when an account is created, the given password is [encrypted here](https://github.com/smpallen99/coherence/blob/master/lib/coherence/schema.ex#L227) and saved in the database (field password_hash) by default. When you login (create new session), the password is validated in the [controller here](https://github.com/smpallen99/coherence/blob/master/web/controllers/session_controller.ex#L70) which calls [the model here](https://github.com/smpallen99/coherence/blob/master/lib/coherence/schema.ex#L221) and finally creates a the [login here](https://github.com/smpallen99/coherence/blob/master/lib/coherence/plugs/authorization/session.ex#L87). 

That function creates a UUID and stores the UUID (key) and the user data (user model) in the session store which is an Agent. The UUID is stored in the session. On each further request, the UUID is pulled out of the session and looked up in the session store Agent. If found, the user data is stored in the `conn.assigns[:current_user]`.

So, as you can see, there is no personal information stored in the session cookie.

As for Phoenix Channel Authentication, I've just started looking at that. I'll create a issue to track this work.

**Comment by jaimeiniesta** [comment]
@leishman did you implement the solution as explained in the wiki? I'm trying to, and after fixing [some typos](https://github.com/smpallen99/coherence/issues/212), I'm not able to log in. I get this error, for a valid user:

`protocol Ecto.Queryable not implemented for nil, the given module does not exist`

in this line of `ecto_db_session.ex`:

`where(@session_model, [s], s.user_id == ^id_str)`

**Comment by jaimeiniesta** [comment]
@leishman fixed it, I forgot to include the `:session_model` and `:session_repo` values in the configuration.

**Comment by jaimeiniesta** [comment]
It still isn't working - it looks like it tries to create a session with a blank user_id, because `id_key` is blank. I'll try to see where this value comes from.

**Comment by yjukaku** [comment]
In case this helps future searchers, `id_key` is likely blank because it is taken from the coherence config's schema_key. `schema_key: :id` should be set in the config.exs.

```elixir
config :coherence,
  #...
  schema_key: :id # must be an atom, not a string!
```
