### ISSUE TITLE
credo?

### ISSUE THREAD

**Issue by bitboxer** [smpallen99/coherence#131]
I just tried to run [credo](https://github.com/rrrene/credo) on this project and it returned 

```
found 5 consistency issues, 2 warnings, 97 refactoring opportunities,
264 code readability issues, 77 software design suggestions
```

What do you think of adding credo to this project and fixing those issues?

**Comment by smpallen99** [comment]
Its a good idea. PR welcome

**Comment by bitboxer** [comment]
Sadly this is too much to do it alone. I would love to share the workload with more people. How should we proceed? Are you willing to help me do the work?

**Comment by bitboxer** [comment]
Ah and for some you have to decide how to fix them. For example the too long and deeply nested method in the `router.ex`

**Comment by bitboxer** [comment]
[This](https://github.com/bitboxer/coherence/tree/add-credo) is the branch where I started working on it.

**Comment by smpallen99** [comment]
@bitboxer Can this issue be closed now?

**Comment by bitboxer** [comment]
Yes and no. Yes because credo is added now, and No because it prints out of issues that need to be fixed. Up to you what to do with it. Just adding credo and keeping all those errors is not ideal in my opinion :wink: .

**Comment by smpallen99** [comment]
@bitboxer Thanks for the heads up

**Comment by bitboxer** [comment]
I am still interested in helping out in the credo and the i18n thing. I just waited for any reaction to this from you. What do you prefer? I can start the i18n anytime. I think that is faster than the credo part. For the credo part I would love to have some guidance on how you would like some credo warnings to be handled.

**Comment by smpallen99** [comment]
@bitboxer i18n would be great. I'm working through the credo warnings now. I'll let you know if I get tired of it. For the credo stuff, I'm down to the following `389 mods/funs, found 77 refactoring opportunities, 9 code readability issues, 1 software design suggestion.`

**Comment by bitboxer** [comment]
Awesome!
