### ISSUE TITLE
Compilation error on install

### ISSUE THREAD

**Issue by charafau** [smpallen99/coherence#136]
Hello, I tried to use coherence plugin as it seems to be the closest thing to rails devise. When I make each step according to manual and run `mix ecto.create` then I got compilation error in unlock_view: 

```
== Compilation error on file web/views/coherence/unlock_view.ex ==
** (CompileError) web/templates/coherence/unlock/new.html.eex:3: undefined function unlock_path/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by danielfoxp2** [comment]
I am having the same error message.

**Comment by danielfoxp2** [comment]
I was able to solve the problem by searching the recent commits and pull request of this project.
So I found this [commit](https://github.com/smpallen99/coherence/commit/99e70925b5a4f6a0c5f9667dda968b1eb8866501)  and this [pull request](https://github.com/smpallen99/coherence/pull/135) related with elixir 1.4 version. I compared my installed files with those commits and saw they were different. Seems like the new version don't work if some parentheses (optional before 1.4) is missing.

So I chase my warning files and put parentheses in each line with problem and used the commit and pull request as base to see if I don't miss anything. 

After that I ran my mix ecto.setup and everything is working like a charm (for now lol).

**Comment by smpallen99** [comment]
@danielfoxp2 So, can I presume it was related to generated controllers in your project. If so, is there anything we can fix in Coherence? or is this just an update docs issue?

**Comment by kimquy** [comment]
I think this issue can be closed. I jump into similar situation today when setup a fresh phoenix project. And the problem came from I have missed config the project. In my case was `I forgot to put this function `coherence_routes` inside my router`

**Comment by x-ji** [comment]
Yeah I encountered this issue too but it seems to be just due to the fact that I didn't modify `router.ex` before trying to run `mix ecto.setup`.
