### ISSUE TITLE
password reset requires current password

### ISSUE THREAD

**Issue by manukall** [smpallen99/coherence#140]
i think if `require_current_password: true`, the current password is required even if the user came via the "forgot password"-functionality. that doesn't make sense.

for now i've worked around this by just setting `require_current_password: false`, as this isn't a hard requirement for me.

**Comment by apoeco** [comment]
Duplicate of #123.

**Comment by manukall** [comment]
@apoeco the PR referenced in #123 only fixed the view, though. the error described above still happens in the controller.

**Comment by manukall** [comment]
@apoeco you're right. will close this issue. thanks
