### ISSUE TITLE
Redirect_to on :session_create should redirect to referrer if one exists

### ISSUE THREAD

**Issue by te-chris** [smpallen99/coherence#147]
Just a suggestion, but I feel like it would be better UX if the redirect on session create first tried to redirect to the route that the user was originally trying to visit, should one exist, before redirecting to the default after `:session_create` route.

**Comment by smpallen99** [comment]
it should already do this. here is the code from `redirects.ex`

```
 def session_create(conn, _) do
        url = case get_session(conn, "user_return_to") do
          nil -> "/"
          value -> value
        end
        conn
        |> put_session("user_return_to", nil)
        |> redirect(to: url)
      end
```

Have you tested this and confirmed that it doesn't work?

**Comment by te-chris** [comment]
Yeah I just tested it.  I try to visit a route logged out, it renders the form, login and redirects to my default path (overridden in my redirects.ex file).
