### ISSUE TITLE
Login Field

### ISSUE THREAD

**Issue by fbutano** [smpallen99/coherence#149]
Is there a simple way to use another field of the User Model for login instead of email?

Francesco

**Comment by smpallen99** [comment]
Yes, [:login_field](https://github.com/smpallen99/coherence/blob/master/lib/coherence/config.ex#L39) config item. Set that in your project's `config/config.exs` file.

**Comment by fbutano** [comment]
Many thanks. It works!! this is my file:
`
config :coherence,
  user_schema: App.User,
  repo: App.Repo,
  module: App,
  logged_out_url: "/",
  login_field: :name,
  opts: [:rememberable, :lockable, :trackable, :authenticatable]

`
Now the login form shows name/password instead of email/password.

**Comment by smpallen99** [comment]
👍
