### ISSUE TITLE
Invalid dependencies?

### ISSUE THREAD

**Issue by tslocke** [smpallen99/coherence#157]
I'm kinda new to Elixir so I may be missing something here, but it looks to me like the coherence dependencies have a problem

Coherence depends on `{:phoenix_html, "~> 2.6"}` and `{:phoenix_swoosh, "~> 0.1.3"}`, but `phoenix_swoosh` 0.1.3 depends on `{:phoenix_html, "~> 2.2"}`, so there's a conflict over the `phoenix_html` version.

Since adding `coherence` to my own mix.exs, `mix deps.get` is failing with "dependency resolution failed"

**Comment by kimquy** [comment]
Can you share your dependencies in your `mix.exs` file ? @tslocke

**Comment by tslocke** [comment]
I fixed it by adding `override: true` to my phoenix_html dependency. 

As you're asking for my `mix.exs`, I assume that what I described above is not a conflict in and of itself. Why is that?

Here are my deps:

    [{:phoenix, "~> 1.2.1"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6", override: true},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:phoenix_slime, "~> 0.8.0"},
     {:coherence, "~> 0.3"},
     {:mailgun, github: "chrismccord/mailgun", branch: "master", override: true}, # Resolve addict/mailgun conflict over Poison version
     {:bodyguard, "~> 0.5.0"},
     {:ex_admin, github: "smpallen99/ex_admin"},
     {:csv, "~> 1.4.2"},
     {:inflex, "~> 1.7.0"},
     {:timex, "~> 2.1"},
     {:arc, "~> 0.6.0"},
     {:ex_aws, github: "CargoSense/ex_aws", override: true},
     {:hackney, "~> 1.6"},
     {:poison, "~> 2.0"},
     {:sweet_xml, "~> 0.6"},
     {:arc_ecto, "~> 0.5.0"}]

**Comment by smpallen99** [comment]
keeping dependencies up to date can be a pain. yes, using override to resolve them is the right approach

**Comment by edevil** [comment]
I also could not run "mix deps.get" successfully, because the currently released coherence version depends on phoenix_timex, which is not up to date.

```
Running dependency resolution...

Failed to use "phoenix_html" (version 2.9.3) because
  coherence (versions 0.3.0 and 0.3.1) requires ~> 2.6
  phoenix_ecto (version 3.2.3) requires ~> 2.9
  phoenix_swoosh (version 0.1.3) requires ~> 2.2
  phoenix_timex (version 1.0.0) requires ~> 2.5.1
  mix.lock specifies 2.9.3


Failed to use "timex" (version 3.1.13) because
  phoenix_timex (version 1.0.1) requires ~> 2.1
  scrape (version 2.0.0) requires ~> 3.0
  mix.lock specifies 3.1.13
```

I've noticed that in the master branch the dependencies have been changed. Is it in a usable state? Or should I wait for a release?

**Comment by smpallen99** [comment]
Yes, master is pretty stable. i'm using it.

If you want to fix the issue on your current project, just add the following to your deps.

```
{:phoenix_html, "~> 2.9.3", override: true},
{:timex, "~> 3.1.13", override: true}
```

You may also want to update the version of :phoenix_timex that may fix the timex version issue.
