### ISSUE TITLE
Coherence.Web.view missing (undefined function registration_path)

### ISSUE THREAD

**Issue by tslocke** [smpallen99/coherence#158]
In coherence/web/web.ex, the `view` function is commented out, which led to `undefined function registration_path` in Coherence.RegistrationView.

I manually put the use/import statements into Coherence.RegistrationView, and managed to get it compiling after removing `import Coherence.ErrorHelpers`

Here's my Coherence.RegistrationView:

    defmodule Coherence.RegistrationView do
      use Phoenix.View, root: "web/templates"
      # Import convenience functions from controllers
      import Phoenix.Controller, only: [get_csrf_token: 0, get_flash: 2, view_module: 1]

      # Use all HTML functionality (forms, tags, etc)
      use Phoenix.HTML

      import Coherence.Gettext

    end

**Comment by OvermindDL1** [comment]
That error would be caused by you not having your router list the registration path, what is your entire router?

**Comment by tslocke** [comment]
Silly mistake - my app isn't `:registerable` anyway - I just deleted `views/registration_view.ex` and `templates/registration_view` and I'm good : )
