### ISSUE TITLE
How to modify one session from another? (e.g. admin disabled an account)

### ISSUE THREAD

**Issue by tslocke** [smpallen99/coherence#160]
Am I right that the session auth stores the entire user record in the session, and not just the ID? Hence the need to call `update_login` if there is a change?

So how do we handle the situation where we want to modify some other session? E.g. an admin disabled an account. Ideally that account should immediately lose access to protected routes.

Thanks : )

**Comment by smpallen99** [comment]
@tslocke You can run the logout user api on the session. that should remove them from the session store so they will not be able to access protected routes anymore. Look at the session controller delete action for example.

**Comment by tslocke** [comment]
My understanding is that you can only do this from the session itself, not from one session to another, so the difficult part is knowing when to do it.

I guess the dumb solution is just to refresh the current user record in the session from the database, before every protected request, e.g. in a plug.

Tom

**Comment by smpallen99** [comment]
There is a new API to update all sessions given a user schema.

`Coherence.CredentialStore.Server.update_user_logins/1`
