### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by gpcweb** [smpallen99/coherence#161]
I just recently deploy my app to heroku, I'm using sendgrid to deliver the emails, but after two hours no email had being delivered.

This is my coherence configuration to send emails:

`config :coherence, Chatter.Coherence.Mailer,
  adapter: Swoosh.Adapters.Sendgrid,
  api_key: {:system, "API_KEY"}`
 
So is there any config that maybe I'm just missing?  Is there any log that I can check to see what is happening??

**Comment by kimquy** [comment]
Got a feeling that you have not config your API key properly. Can you double check that, your app have access to the key. Normally you can set the heroku env key from command line or from the web app.

**Comment by gpcweb** [comment]
The key was setup properly on Heroku besides there are other keys working just fine (e.g. DATABASE_URL)

**Comment by gpcweb** [comment]
Please close this issue, I deploy the app again on heroku and thye emails are working as expected, I guess it was a heroku problem.
