### ISSUE TITLE
Coherence.PasswordController#update/2 does not check if reset token is expired

### ISSUE THREAD

**Issue by fabrik42** [smpallen99/coherence#163]
Hi!

While working on another PR for this project, I think I found another problem:

When resetting the password, the `Coherence.PasswordController#edit/2` function checks, if the password reset token ist not expired:

https://github.com/smpallen99/coherence/blob/master/web/controllers/password_controller.ex#L90

However, the actual `Coherence.PasswordController#update/2` function does not check this. 

https://github.com/smpallen99/coherence/blob/master/web/controllers/password_controller.ex#L108-L137

So it is possible to reset the password with an expired reset token by posting directly to this function.

Best,
Christian

**Comment by smpallen99** [comment]
Good catch

**Comment by fabrik42** [comment]
I included a fix for this problem in #165
