### ISSUE TITLE
Logout link not working

### ISSUE THREAD

**Issue by MFernstrom** [smpallen99/coherence#164]
I've added <%= Syskonskapet.Coherence.ViewHelpers.coherence_links(@conn, :layout) %> in my layout eex file, and I get the username link and a logout link.

When I start the server and visit a protected route, I get the login screen, and I can log in and then see the page.

If I click the username link, I go to the user edit page.

**But the link for logout is just the current page and #, and it doesn't log me out when clicked.**

**Comment by MFernstrom** [comment]
I played around a bit with the Chrome dev tools, and the problem seems to be the generated link.

If I hack in a button to submit the form, it works just fine, but the a href link does not.

**Comment by egeersoz** [comment]
Yeah, the logout link doesn't seem to work out of the box. This is what I do.

app.html.eex layout:

```
<li><a href id="sign-out-button">Sign out</a></li>
<li style="display:none;"><%= link "Sign out", to: session_path(@conn, :delete), id: "logout-form", method: :delete %></li>
```

app.js:

```
$("#sign-out-button").on("click", function(e) {
    e.preventDefault();
    $("#logout-form").parents("form.link").submit();
});
```

Basically, when someone clicks the Log out `<li>` element, I send a `submit()` command to the hidden logout form. It works great.

**Comment by smpallen99** [comment]
This was working, but I did notice last week that its broken. I'm not sure what changed. Looking at phoenix_html docs, it should work. Anyone want to find out the phoenix way of handling logout links?

**Comment by gitten** [comment]
I used the way shown in the Phoenix book, nothing else was required to make the link work.
``` <li><%= link "Log out", to: session_path(@conn, :delete), method: "delete" %></li>```
I am using 0.3.1 from hex repo.

**Comment by tashavanes** [comment]
gitten's method is working for me. Thanks!
