### ISSUE TITLE
Support custom password validations

### ISSUE THREAD

**Issue by Qqwy** [smpallen99/coherence#177]
Right now, on line [245 in Coherence.Schema](https://github.com/smpallen99/coherence/blob/906e1ade0d61403569102b7654685905b56a9d28/lib/coherence/schema.ex#L245), the minimum password length is set to 4 characters.

if I would like my own validations for the password, Should I just add this to the user model? Or override `User.validate_password/2`? The documentation is not really clear on this.

**Comment by smpallen99** [comment]
I have not built in support for password validators. So best to add it to your changeset.
