### ISSUE TITLE
Portuguese (PT and perhaps BR) translation

### ISSUE THREAD

**Issue by tmbb** [smpallen99/coherence#188]
I'd like to translate coherence to pt_PT. I can translate it to pt_BR too, but I might get some parts wrong as there are some subtle differences (e.g. *utilizador* vs *usuário*). Given Elixir's popularity in Brazil I don't think finding someone to review my pt_BR translation will be too hard.

**Comment by smpallen99** [comment]
We decided not to provided canned translations for Coherence. Please review latest comments in #183
