### ISSUE TITLE
Error in coh.install phoenix 1.3.0-rc

### ISSUE THREAD

**Issue by tmbb** [smpallen99/coherence#192]
I'm declaring phoenix 1.3.0-rc as a dependency in the mix.exs file with `override: true`.
The problem seems to e that you're trying to convert a keyword into a string using IO.chardata_to_string/1. (:transcrev is the name of my app)

```
mix coh.install --full-confirmable
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:445: IO.chardata_to_string(:transcrev)
    (elixir) lib/path.ex:475: Path.do_join/3
    (elixir) lib/path.ex:470: Path.join/2
    lib/mix/tasks/coh.install.ex:336: Mix.Tasks.Coh.Install.check_for_model/1
    lib/mix/tasks/coh.install.ex:197: Mix.Tasks.Coh.Install.do_run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

Running on Windows 10

**Comment by smpallen99** [comment]
I'm using Phoenix mix helpers that don't work yet in the the phoenix rc release. That's the problem trying to developer against a pre release version of a dependency.

**Comment by tmbb** [comment]
Oh, I'm sorry. I thought the release candidate was supposed to be supported already :)

**Comment by david-wilson** [comment]
Beat me to posting this by just a few minutes. :) Is there a way to develop using these two pre-release versions together?

**Comment by smpallen99** [comment]
I think I only use one API to get the location of the web path that depends on phoenix master. I could hard code that. It won't be as flexible, but should fix the issue. Give me an hour to try it out.

**Comment by tmbb** [comment]
@smapllen99 please don't waste a lot of time with this! As you said phoenix 1.3 doesn't even have an official release. We should just use master until the changes coherence needs land in 1.3.0rc

**Comment by smpallen99** [comment]
@tmbb Two people already having the issue. I think a change is warranted. Should not be a difficult fix. Just about ready to test it now.

**Comment by smpallen99** [comment]
The issue is with finding web_path. I'm building my own that searches "./web", and "lib/my_project/web". If neither of these exist, I'll raise with a message to use the new "--web-path" option I'm adding.

That will also provide some error checking as a bonus :)

**Comment by smpallen99** [comment]
@tmbb. Can you verify that it works now and close the issue if ur satisfied. Thanks!!

**Comment by david-wilson** [comment]
Works for me now. Thanks!

**Comment by tmbb** [comment]
Works for me too
