### ISSUE TITLE
Custom password_hash column - unknown field `password_hash`

### ISSUE THREAD

**Issue by seanwash** [smpallen99/coherence#193]
### Steps

1. I installed coherence and ran the full installation
2. I then modified the config to use a custom `password_hash` column, `encrypted_password`
3. I ran `mix deps.compile coherence`
4. I try to submit a form at `/sessions/new`
5. I get `unknown field `password_hash`. Only fields, embeds and associations (except :through ones) are supported in changesets`

I also tried setting the config, and reinstalling after a compile. No dice.

### Debugging

When in my user changeset, I use `IO.puts inspect coherence_fields` I see that the first item is `password_hash` and not the custom column name I specified in config.exs. When I use `IO.puts inspect Coherence.Config.password_hash` in that same changeset, I see my custom column name.

### Stack

```
Request: POST /sessions
** (exit) an exception was raised:
    ** (ArgumentError) unknown field `password_hash`. Only fields, embeds and associations (except :through ones) are supported in changesets
        (ecto) lib/ecto/changeset.ex:503: Ecto.Changeset.type!/2
        (ecto) lib/ecto/changeset.ex:474: Ecto.Changeset.process_param/8
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
        (ecto) lib/ecto/changeset.ex:450: Ecto.Changeset.do_cast/7
        (designkollective) web/models/coherence/user.ex:15: Designkollective.User.changeset/2
        (coherence) web/controllers/session_controller.ex:169: Coherence.SessionController.failed_login/3
        (coherence) web/controllers/session_controller.ex:102: Coherence.SessionController.create/2
        (coherence) web/controllers/session_controller.ex:1: Coherence.SessionController.action/2
        (coherence) web/controllers/session_controller.ex:1: Coherence.SessionController.phoenix_controller_pipeline/2
        (designkollective) lib/designkollective/endpoint.ex:1: Designkollective.Endpoint.instrument/4
        (designkollective) lib/phoenix/router.ex:261: Designkollective.Router.dispatch/2
        (designkollective) web/router.ex:1: Designkollective.Router.do_call/2
        (designkollective) lib/designkollective/endpoint.ex:1: Designkollective.Endpoint.phoenix_pipeline/1
        (designkollective) lib/plug/debugger.ex:123: Designkollective.Endpoint."call (overridable 3)"/2
        (designkollective) lib/designkollective/endpoint.ex:1: Designkollective.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/seanwash/Sites/designkollective/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

### Versions
Phoenix 1.2.1
Coherence 0.3

**Comment by seanwash** [comment]
Update, when I run `mix deps.compile coherence --force` things work as expected.

**Comment by smpallen99** [comment]
Just reviewed the code. It does require that your user schema is recompiled. But is should not require recompiling Coherence. Its actually a macro so the field is pulled out of your config at compile time (for performance). 

I'll leave the issue open until I have a chance to test it. I'm glad you got it working 👍
