### ISSUE TITLE
phx-1.3 - existing User schema is not found.

### ISSUE THREAD

**Issue by david-wilson** [smpallen99/coherence#197]
Using Phoenix 1.3 rc and the Coherence phx-1.3 branch, I ran a `mix coh.install --full`. My existing User schema, under lib/accounts/users.ex with the module name MyApp.Accounts.User was not found by the mix task by default. I can modify my existing schema and update the configuration to proceed, but it would be convenient to have User schemas outside the "web" folder detected by default.

**Comment by mdoza** [comment]
I'm starting a Phoenix 1.3 project today. I am looking at Coherence to save time with authentication. However, like you have found out there appears to be no confirmation options for contexts. There appears to be an option to generate controller boilerplate. I haven't tried yet, but I bet the answer is within those generated controllers. I will let you know what I find out.

**Comment by mdoza** [comment]
@david-wilson looking at the `Coherence.Config` module, it looks like you can set the `user_schema` setting. That looks a lot easier than creating broilerplate controllers.

**Comment by hakunin** [comment]
Just tried the 1.3 branch and it worked nicely for me. I had a User there as well but I just moved the code around and changed the config so that was fine.

What I was surprised about was that the User model appeared under the `web` directory and not the project directory.

**Comment by smpallen99** [comment]
yes, I still need to fix that.There are still a few items that need to be resolved before i merge the branch into master.

**Comment by smpallen99** [comment]
Give master a try now. Its now detecting existing schema and if not found, places the generated schema in lib/my_app/coherence/user.ex
