### ISSUE TITLE
OAuth Provider

### ISSUE THREAD

**Issue by gwincr11** [smpallen99/coherence#20]
Hello,

This is looking like a great project! Thanks for building it. I think you have most of what I am looking for, but I also need an OAuth identity provider so an outside application can login a user and then I need to pass it an api key.

Any advice about how to handle this? 

Thanks,
Cory

**Comment by smpallen99** [comment]
I need to get familiar with OAuth. I believe there is already an auth solution that supports OAuth so I'll review that.

**Comment by claudiojulioferraz** [comment]
See [ueberauth](https://github.com/ueberauth/)

**Comment by smpallen99** [comment]
I'm looking at https://github.com/scrogson/oauth2 integration right now. I have not looked at ueberauth yet.

**Comment by gwincr11** [comment]
@claudiojulioferraz I checked out https://github.com/ueberauth/ueberauth_provider but it doesn't seem to exist yet.

@smpallen99 a good example from the rails world is https://github.com/doorkeeper-gem/doorkeeper

**Comment by gwincr11** [comment]
@smpallen99 so https://github.com/scrogson/oauth2 seems to be a client, not a provider. 

Here is a pretty simple explanation of how it OAuth2 works: https://aaronparecki.com/2012/07/29/2/oauth2-simplified

This Rails cast also shows the flow pretty well: https://www.youtube.com/watch?v=zN9BylV81rw

I am just dipping my toe into the Phoenix world but would be open to helping with the implementation if you can put up with my noobness :)

**Comment by britton-jb** [comment]
It's probably worth looking at ueberauth, as suggested by @claudiojulioferraz, because it abstracts a lot of the oauth boilerplate and has a good team behind it.

**Comment by smpallen99** [comment]
Here are my thoughts  on the topic;
Would be nice to have  oAuth provider and consumer support for Coherence
Would be best to leverage existing, proven packages
Perhaps even providing support for multiple packages
Create value add integrate with Coherence, perhaps through an addon like `coherence_uberauth`
For a client integration, we could provide a generator to add prebuilt strategies
For provider, an integration that makes it easy to configure
Ensure these integrations interact appropriately with all the Coherence features
If a package can be used with Coherence without any additional Coherence work, then we document this, perhaps on the github wiki
I’m open to PRs for the base Coherence dev if anything is needed (perhaps some hooks in the controllers?)
Steve

**Comment by gwincr11** [comment]
1. https://github.com/scrogson/oauth2 seems to be a OAuth2 consumer so no need to build that. In fact it probably makes sense to use locally to unit test with.
2. Agreed, but I don't think that their is a provider in the Phoenix eco system.
3. I could see Coherence-OAuth being a different package that is more open ended to work with other auth tools. 
4. I think that prebuilt strategies and generators are the way to go.

I think the only things that will be needed from Coherence would be a redirect process so a user can login and be redirected back to the OAuth page.

**Comment by gwincr11** [comment]
@smpallen99 So I am going to start implementing this to the best of my ability. As I said before I am new to Phoenix so it will be a bit of a learning process.

I am going to build it as a separate package and support Coherence. I have never built a Phoenix package before, do you have any advice or good resources outlining how to do this? Anyone who wants to help is more then welcome!

**Comment by smpallen99** [comment]
@gwincr11 Sounds great! Developing an Elixir package is great experience and a lot of fun. I have couple questions and requests for you.

* can you confirm what your building? Is it the provider part? 
* are you on slack? if not, you might want to create an account and join the Elixir team. We can then have some interactive discussions. I'm @smpallen99 on slack.
* it would be good to hash out a high level approach. For example, are you going to base this in UberAuth? If so, have you had any discussions with that team about contributing a new module to provide provider support?

As for developing a new package, its fairly straight forward:

* Create a new elixir project. If your package is just going to add Elixir modules and generators, then use `mix new project_name`. This is what I recommend. 
* You can take a look at [Coherence](https://github.com/smpallen99/coherence), [Whatwasit](https://github.com/smpallen99/whatwasit), or some other packages to understand how to create mix tasks and how to write tests for them.
* I usually create a test project that uses the package under development to do manual testing and exploratory work.
* In your test project, use the path option in the deps entry to use your local project. Something like `{:my_package, path: "../my_package"}`. With this, if you make a change to the source in your project, it will get recompiled when you restart your test project.
* I sometimes do the dev for a package right in the test project first. Get it working the way I want to, then move the code to the package. This allows you concentrate on the problem without worrying the package part. 
* Start small and refactor as you add new functionality.
* Use other projects for examples Elixir, Phoenix, Ecto, etc.
* Write test as you go!

**Comment by gwincr11** [comment]
@smpallen99 

1. Yes, I am just planning on building the provider portion. I am going to only develop an OAuth2 provider for now and am planning on modeling it after the Doorkeep gem.
2. I just joined the Elixir slack, I am @gwinner.
3. I would be open to putting it in the UberAuth project but have not reached out to them.

Package dev:
1. I will need to add Ecto Models, paths, controllers/routes and views.
2. Is their a nice Phoenix test generator or any documentation?
3. I see you have a Phoenix app in your test folder, is there a starter?
4. Yup, I figured that one out.

I try to test first when I code, but I am pretty unclear how to setup a test environment for this particular type of plugin so that will be the first step. I am also curious how to share Repo's and other things across projects. I know it is a config but I am unclear on how to get that across the project.

I am also wondering if this should be an umbrella project, an elixir project or a Phoenix app.

Thanks,
Cory

**Comment by mathieujobin** [comment]
have you guys tried using https://github.com/mustafaturan/shield ? isn't it exactly what we want ?

**Comment by gwincr11** [comment]
Hi @mathieujobin 

Yes, shield appears to be exactly what we are looking for, although it was not in existience at the time of conversation. Or at least not on our radar.

Cory

**Comment by danschultzer** [comment]
I was looking for a library to handle OAuth login easily with Coherence but didn't find any. So I've built my own that adds multi provider support to Coherence. I hope it can help others save some time and work: https://github.com/danschultzer/coherence_assent
