### ISSUE TITLE
Possible to disable Registerable?

### ISSUE THREAD

**Issue by ziazek** [smpallen99/coherence#205]
Hi, I'm new to Coherence, and I've not been able to disable the Registerable module. (I intend to disable it temporarily until the app is ready for public registrations)

I tried removing `:registerable` from config.exs, but it gave an error about not being able to compile the registration_view.ex. 

Is there a simple way to disable registrations?

**Comment by smpallen99** [comment]
This is a scenario I did not anticipate while developing coherence. You could probably rename the view to `.bak`, and move the registration template directory outside of templates.
