### ISSUE TITLE
Can't edit wiki pages

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#212]
I was going to fix a typo but it looks like we haven't permission to edit.

**Comment by jaimeiniesta** [comment]
What I wanted to fix was, in https://github.com/smpallen99/coherence/wiki/Session-token-Ecto-Persistance:

```
defimpl PlugAuth.DbStore, for: MyProject.User do
```

should be:

```
defimpl Coherence.DbStore, for: MyProject.User do
```

Also, "database is checked **for the for the** user".

Thanks :)

**Comment by jaimeiniesta** [comment]
Also, a closing parenthesis is missing here:

`validate_required(@fields`

**Comment by smpallen99** [comment]
I just enabled public access to the wiki. Also fixed the issues you mentioned above.
