### ISSUE TITLE
Please provide information how to install coherence under Phoenix 1.3 RC2

### ISSUE THREAD

**Issue by acrolink** [smpallen99/coherence#217]

**Comment by smpallen99** [comment]
`{:coherence, githhub: "smpallen99/coherence", branch: "phx-1.3"}`

`mix coh.install <options>`

**Comment by acrolink** [comment]
@smpallen99 

Thank you. I have tried that but what happened is that the model, views, templates were placed on `web` directory right under root (Phoenix 1.2 behavior). When I try to load `/registrations/new` I get `function Entre.User.__struct__/0 is undefined (module Entre.User is not available)`

**Comment by smpallen99** [comment]
If you provide an example project I'll take a look at it.

**Comment by smpallen99** [comment]
closing issue due to no response.l
