### ISSUE TITLE
Facing multiple issues. Unable to install plugin

### ISSUE THREAD

**Issue by Tenzil** [smpallen99/coherence#218]
Hi @smpallen99 , I just couldn't install your plugin, i tried for 5hours still never able to test all features you have provided. In coherence_demo when i run mix test i got the following
== Compilation error on file web/views/coherence/confirmation_view.ex ==
** (CompileError) web/templates/coherence/confirmation/new.html.eex:5: undefined function confirmation_path/2
(stdlib) lists.erl:1338: :lists.foreach/2
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

In other places when i tried installing coherence: 0.3
i got module Example.Coherence.PasswordController is not available
module Example.Coherence.RegistrationController is not available

But i got session controller working fine

Please help me here.

**Comment by smpallen99** [comment]
please see my comments on coherence_demo. If you have issues installing in a new project, please provide details on where you are having the issue. Please include the version phoenix, the command you used to create your project, and which version of coherence you are using.

**Comment by smpallen99** [comment]
closing issue due to no response.
