### ISSUE TITLE
No API to change user data in the credential store

### ISSUE THREAD

**Issue by tmbb** [smpallen99/coherence#229]
There should be a way to change user data in tne credential store independently of the storage mechanism. Currently it's easy to change the user in the repo, but the user must logout and login again to see the changes.

This is important to the new context-related functionality introduced by my PR (https://github.com/smpallen99/coherence/pull/228) so that I can have an update_user function that changes the datastore. I apologize in advance if I'm missing something, but from looking at the code I don't think there is a way to update a credential store that is agnostic to the details.

If there is a way to update the credential store, it should be documented somewhere because it can be useful to outside users.

EDIT: there should be a way to update the credential store *if it exists*, so that we could have a function that could be used to update the repo and at the same time update the session only if it exists

**Comment by smpallen99** [comment]
Is this not what your looking for? https://github.com/smpallen99/coherence#updating-the-user-model

**Comment by tmbb** [comment]
Not exactly. That function requires access to the conn and must be invoked from a controller.
I wanted something that could work outside the controller (something that could be invoked in iex, for example).

What I wanted was:

1. Update the user
2. Change the user model in all sessions belonging to that user

Currently I'm hacking something that simple iterates over the sessions map, looks for sessions that belong to the user and updates those, but I don't know if this might fail with all authenticated types.

Maybe this overcomplicates the design, but it's cool to be able to update the user outside the request cycle and have it reflected in the next request :)

**Comment by smpallen99** [comment]
What's ur use case? Perhaps we need a secondary index based on the user id?

**Comment by tmbb** [comment]
Currently my context generator generates this:

```elixir
defmodule CoherenceTest.MyContextdo

  import Ecto.Query, warn: false
  alias CoherenceTest.Repo

  alias CoherenceTest.MyContext.User

  def current_user(conn) do
    case Coherence.current_user(conn) do
      nil -> nil
      user ->
        map = Map.take(user, [:id, :inserted_at, :updated_at, :name, :email])
        struct(User, map)
    end
  end

  def list_users do
    Repo.all(User)
  end

  def get_user!(id), do: Repo.get!(User, id)

  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()

    # Finally, return the (context-appropriate) updated user
    {:ok, updated_user}
  end

  def delete_user(%User{} = user) do
    Repo.delete(user)
  end

  def change_user(%User{} = user) do
    User.changeset(user, %{})
  end
end
```

The function:

```elixir
  def update_user(%User{} = user, attrs) do
    user
    |> User.changeset(attrs)
    |> Repo.update()
````

Currently doesn't update the Credentials store with the new updated version of the user.
I think it makes sense to do so.

**Comment by tmbb** [comment]
Currently my solution (not in the PR yet) is to get the sessions map like this:

```elixir
sessions = Agent.get(Coherence.CredentialStore.Agent, fn state -> state end)
```

And update the map so that each session that belonged to the "old" user now belongs to the "updated user"

**Comment by smpallen99** [comment]
This does not seem any different than updating the use model with the generated user schema. So, I don't think it a problem unique to your new contexts.

The issue here is that the credential store is separate concern from the context/schema and that is why I've left it separate. I'm trying to think of a use case where we would update the user model outside the "context" of a conn. The only two scenarios I can think of are:

1. A scheduled task
2. A channel request

Short answer. I don't think we want to put this update in the context. Perhaps we need an API to extract the session key and another to update the session store based on the session key and not the conn.

**Comment by tmbb** [comment]
> Perhaps we need an API to extract the session key and another to update the session store based on the session key and not the conn

Actually, an API to extract the session *keys* (there might be more than one session for the same user: different devices, connections in different browsers, etc). I agree we should have something like this. I'm not experienced enough to design it myself, but if you can sketch a design I might be able to implement it for each authentication type.

> I don't think we want to put this update in the context.

Where would you put it? Would you rather create a global coherence function that could be used to update the MyApp.Coherence.User and make that the only way to update the user by default?
I'd prefer a function I could use to update the user in my own context and have it automatically reflected in the Session Store, inside or outside a controller.

Of course the Credential Store only holds the MyApp.Coherence.User schemas, not the MyApp.MyContext.User schema. But that's easy to do: just update the Repo with the MyApp.MyContextUser and afterwards fetch the updated MyApp.Coherence.User from the Repo.

This is what I'm doing now.

Does it make sense?

**Comment by tmbb** [comment]
Th code I have right now is:

```elixir
  def update_user(%User{} = user, attrs) do
    # This function performs 2 steps:
    # 1. Update the user in the Repo
    # 2. Update the user in all sessions that belong to that user
    # This second step is necessary, because otherwise the user would
    # only see the changes after a logout and a login.
    # We want the user to see the changes as soon as it's relevant
    # (a page was reloaded, an AJAX call was made, a notification was sent, etc.)
    # This requires updating the session machinery

    # Step 1: Update the user in the Repo and save the updated user for later
    # This user is a MyApp.MyContext.User (a user belonging to MyContext)
    # TODO: handle the failure case
    {:ok, updated_user} = user
    |> User.changeset(attrs)
    |> Repo.update()

    # Step 2: Update the user in all sessions that belong to that user
    # For this, we must use the user generated by Coherence, and not the User from this context
    # We can just fetch the already updated user from the Repo
    coherence_user = Repo.get!(CoherenceTest.Coherence.User, user.id)
    Logger.debug fn -> inspect(coherence_user) end
    # Update the user in all sessions. Step by step:
    # 1. Get a map with all sessions
    sessions = Agent.get(Coherence.CredentialStore.Agent, fn state -> state end)
    Logger.debug fn -> "Sessions belonging to user:\n" <> inspect(sessions, pretty: true) end
    sessions
    # 2. Filter only the sessions that belong to our user.
    #    We'll be updating those.
    #    There might be more than one such session (TODO: check this)
    |> Enum.filter(fn {_, user_data} -> user_data.id == user.id end)
    # 3. For each of the sessions that belong to our user, replace the user with the new one
    |> Enum.map(fn {credential, _} ->
        Coherence.CredentialStore.Agent.put_credentials(credential, coherence_user) end)
    
    # Finally, return the (context-appropriate) updated user
    {:ok, updated_user}
  end
```

**Comment by tmbb** [comment]
In any case I think I should add an update_login function to the context that uses the conn, do you agree?

**Comment by tmbb** [comment]
This is clearly completely orthogonal to contexts.

So let's forget about contexts and think about what's a reasonable API for Coherence itself.
The contexts functions will necessarily follow that API.

**First**, let me say that coming from python WSGI frameworks, I'm completely biased in favor of *cool stuff* like updating the user session outside a request context even if their use might be limited (you can't pull this easily in most python frameworks without things like Redis, as far as I know).

**Second**, I'm self aware enough to know that doing something just because it's cool is not the smartest thing in the world.

**Third**, I have no concrete use case for these features, except for the fact that users today expect a *realtime* experience from their web apps. I certainly do when it makes sense. Users don't want to logout from the app on their phone after updating the username in their computer. The new username should be visible after clicking the next link, or even right away through Phoenix channels.

That said, my proposals:

# Proposals

## Proposal 1: Update Login, with access to the `conn`

There should be a function `Coherence.update_login/2` function which does something like this:

```elixir
def update_login(conn, updated) do
    apply(Coherence.Config.auth_module,
             Coherence.Config.update_login,
             [conn, updated_user, [id_key: Coherence.Config.schema_key]])
  end
```

### Justification:

I think requiring the user to `apply` coherence config modules is not a very nice API.
Those are implementation details, and could be abstracted into a nicer function.
This is a pretty minor point, though.

### Problems

Even though this brings some usability benefits, it doesn't solve the fundamental problems, which leads me to my second proposal.

1. *It requires access to the `conn`, which means it can only be used in a controller*. It doesn't allow one to update user sessions from scheduled tasks, channel context or from an admin dashboard

2. *Even if invoked from a controller (with access to the `conn`), it updates only that session*. If the user has another active session (another device, another browser window), changes are not reflected in that session. This requires the user to logout and login from those devices so that changes are reflected. Well, phoenix is supposed to be a framework for real time applications and I think we should embrace realtime. In the realtime world, the user doesn't need to logout to sync sessions. Actually, in the realtime world, changes would be broadcast from the server to all devices, but that's probably outside the Coherence's scope.

## Proposal 2: Updating All User Sessions

There should be a function named `Coherence.update_all_user_sessions/1` (or `update_all_logins`) that takes the updated User as an argument and updates all sessions belonging to that user. Something like this:

```elixir
def update_all_user_sessions(updated_user) do
    # Coherence.CredentialStore.Agent is probably too low level for this, but it gets the point across
    # Get all sessions (from all users)
    sessions = Agent.get(Coherence.CredentialStore.Agent, fn state -> state end)
    sessions
    # 2. Filter only the sessions that belong to our user.
    #    We'll be updating those.
    #    Remember, there might be more than one such session
    |> Enum.filter(fn {_, user_data} -> user_data.id == updated_user.id end)
    # 3. For each of the sessions that belong to our user, replace the user with the new one
    |> Enum.map(fn {credential, _} ->
          Coherence.CredentialStore.Agent.put_credentials(credential, updated_user)
          credential
        end)
    :ok
  end
```

### Justification

It solves the problems in **Proposal 1**:

1. It can be used from scheduled tasks, channel contexts and admin interfaces
2. It updates all sessions belonging to that user, and not only the session belonging to the `conn`

### Problems

For thousands (or tens of thousands) of concurrent users, this might not be very efficient, because it's linear on the number of active user sessions. It might also be a little inefficient in terms of memory usage. I haven't run any benchmarks on this, but in case this is a problem in practice, I have a third proposal, conditional on efficiency being a problem after benchmarking this properly.

## Proposal 3: Increase efficiency of User lookup

As you've suggested,

> Perhaps we need a secondary index based on the user id?

An index is certainly one of the simplest ways to improve lookups.

My suggestion is to have a two `Map`s:

1. a `Map` that maps `credentials` to `users`
2. an index `Map` that maps each `user.id` to a list of `credentials`

### Justification

The index map would need to be updated each time a session is created or destroyed, but that can be done efficiently. This makes updating all sessions linear on the *number of user sessions* instead of the number of users. Maybe there is a simpler and more efficient solution using something like ETS, but this seems reasonably simple and efficient, and once this is properly abstracted, changing the implementation is simple.

It might have some benefits in memory usage if it reduces copying

### Problems

It would complicate the code, and maybe require the use of a GenServer instead of an Agent. I don't think this should be an argument against implementing this if efficiency is a problem.

**Comment by tmbb** [comment]
I've submitted a pull request (https://github.com/smpallen99/coherence/pull/243) that addresses all points above. It replaces the Agent with a GenServer with an index as described in Point 3.

**Comment by smpallen99** [comment]
Merged.
