### ISSUE TITLE
Misleading/wrong typespecs?

### ISSUE THREAD

**Issue by tmbb** [smpallen99/coherence#230]
In these files:

- [coherence/lib/coherence/plugs/authorization/credential_store/session.ex](https://github.com/smpallen99/coherence/blob/master/lib/coherence/plugs/authorization/credential_store/session.ex)
- [coherence/lib/coherence/plugs/authorization/credential_store/agent.ex](https://github.com/smpallen99/coherence/blob/master/lib/coherence/plugs/authorization/credential_store/agent.ex)

the `credentials` parameters seems to be a `String.t` coresponding to the hex of a UUID.
However, the typespecs say it's a `Map.t` or a `HashDict.t` (which btw seems to have been deprecated):

```elixir
  @doc """
  Puts the `user_data` for the given `credentials`.
  """
  @spec put_credentials(Map.t, t) :: t
  def put_credentials(credentials, user_data) do
    Agent.update(__MODULE__, &Map.put(&1, credentials, user_data))
end
```

I think this code is updating the state of the agent (which is a `Map.t`) with a key of type `String.t` (from inspecting the state of the agent) with a value that's an Ecto schema (a user, in this case).

So, unless I'm misinterpreting something (completely possible, of course), the type spec should read:

```elixir
@spec put_credentials(String.t, t) :: t
```

**Comment by smpallen99** [comment]
Agree. I'm open to a PR.

**Comment by tmbb** [comment]
My pull request corrects these `@spec`s and adds a `credentials` type (actually just a `String.t`). I think it enhances readability. If you don't want to merge my pull request, I can write a new one correcting only this "bug".

**Comment by smpallen99** [comment]
Merged.
