### ISSUE TITLE
File missing the project name in defmodule

### ISSUE THREAD

**Issue by ramka001** [smpallen99/coherence#231]
The coherence module creation is having a problem.  It is not correctly naming the defmodule in accordance to the package in which it is created in.

For example if my project name is called Test,  the CoherenceView full file name should be created in the package   views/coherence/coherence_view

and the code should contain

`defmodule Test.Coherence.CoherenceView do`
`  use Test.Coherence.Web, :view`
`end`

However, when the code is generated, it only contains

`defmodule Coherence.CoherenceView do1`
 ` use Test.Coherence.Web, :view `
`end`

This is causing a compilation error. All the files that are created by the Coherence are missing the project name. I had to manually add them for the compilation to work

**Comment by smpallen99** [comment]
This is the currently designed behaviour of Coherence, however, I do think it should be changed to include the project's namespace as you suggested. 

I've never had any compile issues though in any of the many personal projects that use coherence, nor would I know how to reproduce your issue. Please review [Reporting Bugs](https://github.com/smpallen99/coherence/blob/master/CONTRIBUTING.md#bug-reports) for reporting future Coherence issues.
