### ISSUE TITLE
Compile error with module Chatter.Web.Gettext

### ISSUE THREAD

**Issue by RyanKim01** [smpallen99/coherence#232]
Hi,

After installing the coherence in my Phoenix app, I ran `mix phoenix.server` to start the server. I haven't done any customization yet but following `Get Started` section in coherence.

I get an error msg saying:
```
== Compilation error on file lib/chatter/web/emails/coherence/user_email.ex ==
** (CompileError) lib/chatter/web/emails/coherence/user_email.ex:9: module Chatter.Web.Gettext is not loaded and could not be found
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

Any guess why this is happening? Not sure why the module is not being loaded.

Lastly, here is a separate a question. Whenever I run `$ mix coh.install --full-invitable` in the project directly, I get asked  `Cannot find web path lib/(app name)/web. Are you sure you want to continue? [Yn] ` and I proceed with Yes. Is this a normal phenomenon?

**Comment by smpallen99** [comment]
Please use `mix coherence.install` on a non phoenix 1.3 project instead of `mix coh.install`.

**Comment by RyanKim01** [comment]
Worked like a charm. Closing the issue. It would be helpful to mention in the get started that people who are using Phoenix (<1.3) should run `coherence` rather than `coh` until the stable version of Phoenix 1.3 comes out. Thanks again.
