### ISSUE TITLE
Mailer configuration issues

### ISSUE THREAD

**Issue by pdelanauze** [smpallen99/coherence#233]
Having issues getting the mailer configuration picked up by coherence, started digging into the source but spotted this along the way : 

https://github.com/smpallen99/coherence/blob/4b6ed2e0f5fe55097a21dfde9849ffb770234899/lib/coherence/config.ex#L216-L216

```elixir
def mailer? do
  !!Application.get_env(:coherence, CoherenceDemo.Coherence.Mailer)
end
```
I'm still getting acquainted with the codebase, but shouldn't this be something else than CoherenceDemo ?

**Comment by cc3c** [comment]
I have the same problem. I can solve it in local changing
!!Application.get_env(:coherence, CoherenceDemo.Coherence.Mailer)
by
!!Application.get_env(:coherence, MyApp.Coherence.Mailer)
But that is not a long term sollution.

**Comment by raulintosh** [comment]
In Coherence.ControllerHelpers module in line 155, must change
email = apply(Module.concat(Config.module, Coherence.UserEmail), fun, [model, url])
to
email = apply(Module.concat(Config.module, Web.Coherence.UserEmail), fun, [model, url])

**Comment by smpallen99** [comment]
I just merged a PR that should fix this issue. Please confirm with master and close the issue. 

Thanks, Steve
