### ISSUE TITLE
In the session store, change 'credentials' for something else

### ISSUE THREAD

**Issue by tmbb** [smpallen99/coherence#235]
I was wondering if credentials is the right name for the keys of the session store.

It's a plural, which makes it awkward to refer to more than one credentials. It makes sense to talk about multiple credentialsS because a user might have more than one session.

Something like *session_id* or *session_key* might be better. The session store is just a map from a *session_id*/*session_key* to a user. It is much more comfortable to write about all the *session_keys* belonging to the user (or belonging to sessions that belong to the user).

I'm currently working on facilities to change the user login in all sessions belonging to that user, and not having a sane plural makes it harder to find good names.

**Comment by smpallen99** [comment]
I'm not completely sold on the requested name change. I do understand the dilemma. I'm sure there is a name that could reference  your intent. Perhaps `user_credentials`, `users_creds`, `all_creds_for_user`, etc.

**Comment by tmbb** [comment]
> I'm sure there is a name that could reference your intent. 

Yes, of course. But it's awkward, that's all. I'm currently using `sessions_credentials`, as in "credentials belonging to all the sessions).
