### ISSUE TITLE
Coherence.SessionController.init/1 is undefined 

### ISSUE THREAD

**Issue by Teifion** [smpallen99/coherence#245]
I'm getting the following error trying to load the login page

```
function CentaurWeb.Coherence.SessionController.init/1 is undefined
(CentaurWeb.Coherence.SessionController is not available)
```

I've just upgraded my application from phoenix 1.2 to 1.3 and have gotten non-coherence related pages to load.

I used `mix coh.install --reinstall` and and have searched for everything I can think of.

Coherence config section:
```
config :coherence,
  user_schema: CentaurWeb.User,
  repo: Centaur.Repo,
  session_model: CentaurWeb.Session,
  session_repo: Centaur.Repo,
  layout: {CentaurWeb.LayoutView, :blank},
  module: CentaurWeb,
  user_token: true,
  messages_backend: CentaurWeb.Coherence.Messages,
  logged_out_url: "/",
  email_from_name: "<<<>>>",
  email_from_email: "<<<>>>",
  opts: [:rememberable, :authenticatable, :recoverable, :lockable, :trackable, :unlockable_with_token, :invitable, :registerable]
```

I'm using coherence 0.4 and ran `mix deps.update --all` before running the `mix coh.install --reinstall` command.

Cheers

**Comment by smpallen99** [comment]
coherence 0.4.0 the released version of phoenix 1.3. Give the master branch a try.

**Comment by Teifion** [comment]
Thanks for the quick reply.

Please forgive my ignorance, how do I swap? I thought I was using the 1.3 appropriate version already with `{:coherence, "~> 0.4"},`

**Comment by smpallen99** [comment]
`{:coherence, github: "smpallen99/coherence"},`

**Comment by Teifion** [comment]
I've installed it and it didn't work. To check I deleted the folder in deps and my _build folder to ensure it wasn't a caching issue.

The exact traceback is 
```
15:51:59.045 [error] #PID<0.9264.0> running CentaurWeb.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /sessions/new
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function CentaurWeb.Coherence.SessionController.init/1 is undefined (module CentaurWeb.Coherence.SessionController is not available)
        CentaurWeb.Coherence.SessionController.init(:new)
        (centaur) lib/centaur_web/router.ex:1: anonymous fn/1 in CentaurWeb.Router.__match_route__/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (centaur) lib/centaur_web/endpoint.ex:1: CentaurWeb.Endpoint.plug_builder_call/2
        (centaur) lib/plug/debugger.ex:99: CentaurWeb.Endpoint."call (overridable 3)"/2
        (centaur) lib/centaur_web/endpoint.ex:1: CentaurWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /home/teifion/programming/elixir/alacrity/apps/centaur/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```
Having been spending more time trying to work it out on my end I've come to the assumption I must have done something wrong with the router or the web files, I've uploaded mine to a gist since it's easier to read them there: https://gist.github.com/Teifion/d6c4f3ceea5ba781448b9d6607e72eea

If there are any other files or code I can supply to help debug this I'd be delighted to.

**Comment by smpallen99** [comment]
Did you originally generate coherence controllers for your project? If so, try running the reinstall again with the `--controllers` option. If you don't have controllers generated, then you have an incorrect namespace scope on your router.

**Comment by Teifion** [comment]
Thank you for this, it's resolved the immediate issue though I'm getting errors now about some paths not being defined `password_path` for example.

If we look at the output to my terminal:
```
Generated centaur app
* creating priv/repo/migrations/20170731150437_create_coherence_user.exs
* creating lib/centaur/coherence/user.ex
* creating lib/centaur_web/coherence_web.ex
lib/centaur_web/coherence_web.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/coherence_messages.ex
lib/centaur_web/coherence_messages.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/views/coherence/coherence_view.ex
lib/centaur_web/views/coherence/coherence_view.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/views/coherence/layout_view.ex
lib/centaur_web/views/coherence/layout_view.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/views/coherence/coherence_view_helpers.ex
lib/centaur_web/views/coherence/coherence_view_helpers.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/views/coherence/session_view.ex
lib/centaur_web/views/coherence/session_view.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/templates/coherence/layout/app.html.eex
lib/centaur_web/templates/coherence/layout/app.html.eex already exists, overwrite? [Yn] n
* creating lib/centaur_web/templates/coherence/layout/email.html.eex
lib/centaur_web/templates/coherence/layout/email.html.eex already exists, overwrite? [Yn] n
* creating lib/centaur_web/templates/coherence/session/new.html.eex
lib/centaur_web/templates/coherence/session/new.html.eex already exists, overwrite? [Yn] n
* creating lib/centaur_web/controllers/coherence/redirects.ex
lib/centaur_web/controllers/coherence/redirects.ex already exists, overwrite? [Yn] n
* creating lib/centaur_web/controllers/coherence/session_controller.ex
```

We can see it only creates the session controller, it's not created the others. I manually copied those across but there's still an issue so I'm wondering if there's something in the router either missing or that I've made a mistake with.

**Comment by Teifion** [comment]
I've gotten it working; I found two problems:
1 - The templates I was using needed to be updated, I'm not sure why Coherence didn't overwrite them
2 - The config block was duplicated, the following was added to the end of the file, an existing similiarly wrapped block already existed

```
# %% Coherence Configuration %%   Don't remove this line
config :coherence,
  repo: Centaur.Repo,
  module: Centaur,
  web_module: CentaurWeb,
  router: CentaurWeb.Router,
  
  logged_out_url: "/",
  opts: [:authenticatable]
# %% End Coherence Configuration %%
```

Thanks again for your help, I really appreciate it and if there's some low hanging fruit I'd love to have a go at contributing to the library :)

**Comment by smpallen99** [comment]
Glad you got it working. One thing to keep in mind is that the routes the router exposes is based on the opts configured in `config/config.exs`. If you have templates generated for a superset of these opts, then you will get warnings since the templates with be accessing router helpers on that are not  defined (based on the opts setting). 

Also the install/reinstall won't remove templates if you run it on a subset of the options that were previously run. Perhaps that is the scenario you ran into. I'll add an issue to address this issue.
