### ISSUE TITLE
Re-send confirmation link

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#25]
In case the confirmation link wasn't received (email error, caught in spam folder, etc.) or in case it's expired, users need a way to re-send the confirmation link.

**Comment by agustif** [comment]
Yup, was coming here to report the same since I was testing Swoosh.Mailgun with no luck, so I couldn't actually never log in. (Never got my confirmation email)
I will try again with Local Mailer, but this should definitely be on the roadmap.

let us know what would be the best path to help get this done.

**Comment by smpallen99** [comment]
Where do you think "re-send confirmation email" should be presented?

1. On the login form if someone tries to log into to an account that has not been activated
2. On the registration page if the email is found and the account has not been confirmed.
3. Both 1. and 2.
4. Other options

**Comment by agustif** [comment]
In my real life experience, both.

1. a Recover my password / Forgot my password link is enough I think.
2. I think is a really good idea to put a notice where the email is stated clearly in a large bold font. People often misspell on the registration process and are oblivious to it until a human engages conversation with them. I think there are some services like twitter that manage that well, letting a newly created user to change it's email if it hasn't yet been confirmed.

**Comment by smpallen99** [comment]
@agustif I'm not following. 
1. how does "Recover my password" relate to resend confirmation instructions?
2. Can you explain your item 2. further?

**Comment by jaimeiniesta** [comment]
@smpallen99 I think that [1] is enough - not being able to log in because confirmation is pending is a login problem, not a registration problem.

**Comment by smpallen99** [comment]
I ended up putting a "Resend confirmation email" link on the login page. I think this is the most obvious place to find the link.

**Comment by smpallen99** [comment]
I need to change one more thing. If you try to login and have not yet confirmed your password, I'm going to go back to the session new page since that is where the link is to resend the confirmation email.
