### ISSUE TITLE
How can I use the general app layout?

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#26]
Coherence comes with its own app layout, but I'd rather use the general layout, how can I customize this?

**Comment by smpallen99** [comment]
All coherence templates are generated into your project's `web/templates/coherence` directory. You will find a `layout/app.html.eex` file there which you can change.

**Comment by jaimeiniesta** [comment]
Thank you, I had seen that, but I don't want to use a separate layout for the authentication, I want to use the same layout as the rest of the application.

I could duplicate `web/templates/layout/app.html.eex` into `web/templates/coherence/layout/app.html.eex`, but that would be duplicating code, I'd prefer to avoid that if possible.

**Comment by smpallen99** [comment]
If you edit your `web/coherence_web.ex` file and change 
```elixir
use Phoenix.View, root: "web/templates/coherence"
``` 
to 
```elixir
use Phoenix.View, root: "web/templates/"
``` 
then it should pickup your `web/templates/layout/app.html.ex` file

**Comment by smpallen99** [comment]
The other option for complete control over customization is to generate the controllers (with the `--conttrollers` option) into your project. You will then have complete control over coherence. If you do generate controllers, remember to change your route scoping per the README file.

**Comment by jaimeiniesta** [comment]
Thank you, if I change the root configuration for the templates then it does pick the app layout, but then I'll have to move the rest of the Coherence templates to the main folder, of course, I prefer to keep them where they are.

Generating the controllers could be an option but that's overkill in this case.

By now I think I'll just duplicate the layout template, thanks.

**Comment by smpallen99** [comment]
Yes, I made an error. Just edited the post with instructions that should work. Basically, you just need to change the template path for the coherence layout view.

**Comment by jaimeiniesta** [comment]
Thanks, now it works like a charm :)

**Comment by jaimeiniesta** [comment]
Uh, with this change, now the email rendering view is broken, if I try to reset a password I get this error:

```elixir
Could not render "email.html" for Coherence.LayoutView, please define a matching clause for render/2 or define a template at "web/templates/layout". The following templates were compiled:

* app.html

Assigns:

%{email: %Swoosh.Email{assigns: %{layout: {Coherence.LayoutView, "email.html"}, name: "User", url: "http://localhost:4000/passwords/mU8RcJAU8DxhGV1csJf16OrTceCnhTVjv6XxCxw3MKEl1vbK/ed
```

I'll go back to duplicating the layout by now.

**Comment by smpallen99** [comment]
Just move the email template from templates/coherence/layout to templates/layout

**Comment by jaimeiniesta** [comment]
Solved! Thanks!

**Comment by AdrianRibao** [comment]
Please, add this to the docs because I think it's a common issue for people starting that is new to phoenix.

Thanks!

**Comment by Mehonoshin** [comment]
Hi!
I'm going to add some documentation related to templates customization. To make it easier for rails(devise) switchers.

**Comment by jhonathas** [comment]
I do not know if you can help, but I solved it like this:

I changed my default web.ex including at the end:

```
  defmacro __using__([type: :view, template_for: :coherence]) do
    apply(__MODULE__, :view, [:coherence])
  end
```

**Do not remove the `defmacro __using__` that already exists.**

And I changed my view function, still on the web.ex, which looks like this:

```
def view(template \\ :default) do # Change for this

    # Include this
    template_path =
      case template do
        :default   -> "web/templates"
        :coherence -> "web/templates/coherence"
      end

    quote do
      use Phoenix.View, root: unquote(template_path) # Change for this

      import Phoenix.Controller, only: [get_csrf_token: 0, get_flash: 2, view_module: 1, action_name: 1, controller_module: 1]

      use Phoenix.HTML

      import MyProject.Router.Helpers
      import MyProject.ErrorHelpers
      import MyProject.Gettext

      import MyProject.Coherence.ViewHelpers
    end
  end
```

My Coherence.LayoutView is like this:

```
defmodule Coherence.LayoutView do
  use MyProject.Web, :view
end
```

And all the other modules, such as SessionView are like this:

```
defmodule Coherence.SessionView do
  use MyProject.Web, type: :view, template_for: :coherence
end
```

---- 
Note that when I want to use the default path, I do the normal way:
`use MyProject.Web, :view`

Already when I want to use the  Coherence layout, I do so:
  `use MyProject.Web, type: :view, template_for: :coherence`



Hope it helps, and if you have any improvement tips, I appreciate it.

**Comment by jhonathas** [comment]
Now that I have seen Mehonoshin's solution, it was very similar. I had not seen it, and I re-created the wheel. LOL

**Comment by GildedHonour** [comment]
The name of my layout  isn't `my_app.html.eex`

How do I tell Phoenix to use `my_app.html.eex` instead of `app.html.eex` ?
