### ISSUE TITLE
Ecto version incompatibility

### ISSUE THREAD

**Issue by raybradley** [smpallen99/coherence#272]
Hi, I'm new to Elixir, Phoenix, and Coherence. With brand-new versions of Phoenix and Coherence, attempting mix deps.get yields:

```
Failed to use "ecto" (version 2.2.1) because
  coherence (versions 0.4.0 and 0.5.0) requires ~> 2.0
  phoenix_ecto (version 3.2.3) requires ~> 2.1
  timex_ecto (version 3.1.1) requires ~> 2.1.0
  mix.lock specifies 2.2.1
```

Does Coherence need to relax its ecto version requirement?

**Comment by jakub-zawislak** [comment]
I just started a new project and got the same issue. I have fixed this by adding `{:ecto, "~> 2.1", override: true}` to dependencies

**Comment by sivagollapalli** [comment]
Looks like this issue has been fixed. Just now I tried to setup with phoenix `1.3`. It worked without any installation issues. I hope this can be closed.

**Comment by pdgonzalez872** [comment]
@raybradley is this still an issue? Seems like it was solved. If so, could you please close it? Thanks!

**Comment by raybradley** [comment]
Sorry about that!
