### ISSUE TITLE
Documentation for master still specifies version 0.4

### ISSUE THREAD

**Issue by stretchkennedy** [smpallen99/coherence#273]
https://github.com/smpallen99/coherence#installation says to add the line `def deps do [{:coherence, "~> 0.4"}] end` to mix.exs, which is a little confusing because master isn't 0.4, and 0.4 isn't compatible with a newly created phoenix project.

**Comment by dyyce** [comment]
which version is the correct one?

**Comment by smpallen99** [comment]
I've merged PR that changes version to 0.5
