### ISSUE TITLE
Help Needed: Setting up SMTP

### ISSUE THREAD

**Issue by Sathras** [smpallen99/coherence#278]
I am trying to get coherence working on my phoenix 1.3 app using the SMTP adapter.
I added
```
{:swoosh, "~> 0.9.1"},
{:gen_smtp, "~> 0.12.0"},
```
to mix.exs

I believe I also configured the config.exs correctly:
```
# %% Coherence Configuration %%   Don't remove this line
config :coherence,
  user_schema: App.Coherence.User,
  repo: App.Repo,
  module: App,
  web_module: AppWeb,
  router: AppWeb.Router,
  messages_backend: AppWeb.Coherence.Messages,
  logged_out_url: "/",
  email_from_name: {:system, "SMTP_NAME"},
  email_from_email: {:system, "SMTP_EMAIL"},
  opts: [:authenticatable, :recoverable, :lockable, :trackable, :unlockable_with_token, :confirmable, :registerable],
  user_token: true

config :coherence, AppWeb.Coherence.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: {:system, "SMTP_SERVER"},
  username: {:system, "SMTP_EMAIL"},
  password: {:system, "SMTP_PASSWORD"},
  tls: :always,
  auth: :always

# %% End Coherence Configuration %%
```
However Users are properly created and in the debug log i can see the email content in the logger. However no email has ever been send.

Anyone got a clue? I would appriciate!

**Comment by x-ji** [comment]
Did you get this working eventually? It seems that coherence can't detect my mailer configuration for some reason. The app keeps prompting "mailer configuration required", and `Coherence.Config.mailer?` returns `false`. However, I'm pretty sure I finished the configuration just as shown in the example and also as shown in your code snippet above.

**Comment by Sathras** [comment]
unfortunately not. it doesn't seem to reach my smtp server (always getting
timeout). Tried Gmail and my own one. :(
