### ISSUE TITLE
Taking a development break?

### ISSUE THREAD

**Issue by carterbryden** [smpallen99/coherence#291]
Hi @smpallen99 no pressure or anything, just noticed you haven't committed anything for a couple months and wondering if you're taking a break on coherence development or if somethings come up. Hope everything's alright.

**Comment by lorenzosinisi** [comment]
@carterbryden, following

**Comment by lorenzosinisi** [comment]
@smpallen99 if you need any help, just ping me 💃

**Comment by carterbryden** [comment]
@smpallen99 Thanks for the update! Let know if I can help as well.

**Comment by smpallen99** [comment]
I have not had much time for open OOS projects for a while. Spend some time a last week on exadmin. I'll try to put in a little time on coherence this week.

**Comment by smpallen99** [comment]
I've merged all the PRs that are mergeable.

**Comment by smpallen99** [comment]
Just released 0.5.1
