### ISSUE TITLE
Create or alter Users table

### ISSUE THREAD

**Issue by isjaylee** [smpallen99/coherence#3]
Any opposition to creating a Users table versus altering? Thinking it might be easier than having to deal with conflicting column names, unique indexing email, etc.

**Comment by smpallen99** [comment]
@isjaylee I'm planning on a feature that will check to see if your user model already exists. if it does, I'll create the alter migration. It it does not exist, I'll add a create migration. I'll keep this issue open to track that feature.

**Comment by smpallen99** [comment]
Done
