### ISSUE TITLE
Simpler router definition

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#30]
Thanks again for Coherence, it's working great so far, there's just one thing that took me a while to understand, and that is the router definition in the README.

From what I've understood, your proposal is to have 2 similar pipelines, one of which will be used to require authentication (`:browser` in the example), and the other one (`:public`) to just get the authenticated user if it's present, but not require it.

Then, we need to duplicate / scatter the routes depending on the ones that require a user and the ones that don't require it.

In my opinion, this is a job that is better solved at the controller level, by inserting a plug to require authentication on selected actions. I've seen that the `Coherence.Authentication.Session` plug can be used that way too, but as in the README example it shows the router example so prominently, I think it would be better to explain both options.

What I don't like from this approach is that the routes aren't as readable, and the resources need to be defined in 2 different places. Imagine for example, an app that has posts and comments. For both resources, `:index` and `:show` won't require login, but the rest of the actions will. We'll then have:

```elixir
defmodule MyProject.Router do
  use MyProject.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, login: true
  end

  pipeline :public do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  scope "/" do
    pipe_through :public
    coherence_routes :public
  end

  scope "/" do
    pipe_through :browser
    coherence_routes :private
  end

  scope "/", MyProject do
    pipe_through :public

    resources "/posts", PostController, only: [:index, :show] do
      resources "/comments", CommentController, only: [:index, :show]
    end
  end

  scope "/", MyProject do
    pipe_through :browser

    resources "/posts", PostController, except: [:index, :show] do
      resources "/comments", CommentController, except: [:index, :show]
    end
  end  
end
```

Instead, if we plug the requirement in the controller actions, routes can be so much more readable:

```elixir
defmodule MyProject.Router do
  use MyProject.Web, :router
  use Coherence.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  scope "/" do
    pipe_through :browser
    coherence_routes
  end

  scope "/", MyProject do
    pipe_through :browser

    resources "/posts", PostController do
      resources "/comments", CommentController
    end
  end
end
```

Also, the naming of the pipelines confused me, why was the one that required authentication called `:browser`? I guess `:private` would have been a better option?

Anyway, just wanted to share my opinion here. I think it's great that we have the option to plug authentication requirement where it better fits the project, but in my opinion that was a little confusing, at least for me coming from Devise :)

**Comment by smpallen99** [comment]
@jaimeiniesta Thank you for such a clear, concise, and detailed feedback. I understand all your points. I'll review this soon and make some documentation changes. 

I suppose my choice of protecting the browser pipeline and making a public one can be debated :)

**Comment by bolandrm** [comment]
If you add the plug at the controller level, isn't there a chance you'll forget to add it to a controller?  Seems like there would also need to be a check that authentication was either enabled or disabled for every action as well.

**Comment by jaimeiniesta** [comment]
Sure, the advantage of defining it at the router level is that you add it in one place and can't forget to add it later at every controller/action, but you could also forget to add the route to the private pipeline and put part of the routes under the public pipelines... But that's what tests are for, in my opinion.

As I said before, I think it's good that Coherence gives you both options, you can plug this authentication requirement in the router or in the controllers. In my particular case, most routes in my app are public and I just need to protect a few actions, but in your case it might be different, of course :)

**Comment by smpallen99** [comment]
Good discussion. Since this is issue is mainly about documenting the options, it will be up to the programmer to decide which option they want to use based on their project's requirements.

**Comment by smpallen99** [comment]
@jaimeiniesta You need to be careful with the simplified example you provided above. By included unrestricted access to all the coherence_routes, you may not have routes protected that were designed to be. Of course, this depends on the options you installed. 

The following routes are meant to be protected: 

```elixir
      if mode == :all or mode == :protected do
        if Coherence.Config.has_option(:invitable) do
          resources "/invitations", Coherence.InvitationController, only: [:new, :create, :edit]
          post "/invitations/create", Coherence.InvitationController, :create_user
          get "/invitations/:id/resend", Coherence.InvitationController, :resend
        end
        if Coherence.Config.has_option(:authenticatable) do
          resources "/sessions", Coherence.SessionController, only: [:delete]
        end
      end
```

You can, however, get around this by generating the controllers and adding the appropriate plugs in the controllers.

**Comment by jaimeiniesta** [comment]
@smpallen99 thanks for the warning, in my example I was focused on how the routes to my resources were affected, but wasn't so conscious about the assumptions that the Coherence controllers make about their routes.
