### ISSUE TITLE
Reset password e-mail not working

### ISSUE THREAD

**Issue by stenionobres** [smpallen99/coherence#303]
Hi, everyone!

I'm working on a system using Coherence with a friend. Now we need to send the reset password e-mail. 

However, despite the messages saying it was sent successfully, nothing happens in my testmail box.

My config:

config :coherence,
  user_schema: my_app.User,
  repo: my_app.Repo,
  module: my_app,
  logged_out_url: "/",
  email_from_name: "my_app",
  email_from_email: "my_email",
  opts: [:registerable, :trackable, :recoverable, :invitable, :authenticatable]

config :coherence, MyApp.Coherence.Mailer,
  adapter: Swoosh.Adapters.Mailgun,
  api_key: "key-#{my_key}",
  domain: "sandbox#{large_hex_hash}.mailgun.org"

We tried to use the standard option with sendgrid first and the same happened. Was created a sendgrid account and mailgun account. A test with curl worked sending email to my test email box.

What are we forgeting?

![confirmation-message](https://user-images.githubusercontent.com/9358882/32680492-12216628-c652-11e7-9089-0f940d989e4d.png)

**Comment by krzysztofbialek** [comment]
I have same issue with `smtp` adapter using SES

```
config :coherence, ArtrageWeb.Coherence.Mailer,
   adapter: Swoosh.Adapters.SMTP,
   domain: "bookrage.org",
   relay: "email-smtp.us-east-1.amazonaws.com",
   port: 587,
   user_name: "username",
   password: "password",
   sender: "support@bookrage.org"
```

**Comment by stenionobres** [comment]
Hi everyone. After buy a domain and put in the Coherence configuration the email was sent normally.

We needed to configure the domain in Mailgun platform too.
