### ISSUE TITLE
Cut new release with JSON/api support?

### ISSUE THREAD

**Issue by nimish** [smpallen99/coherence#307]
It'd be nice to have that in the hex packages. Depending on master isn't great but I do need the json behavior based stuff.

There's some stuff that needs to be added to the `coh.install` to get the api stuff working properly but it's not complex.

**Comment by veverkap** [comment]
Is there any update to this?  Is the master good to use in production if not?

**Comment by smpallen99** [comment]
I believe the responder feature which has been in master for a while now should give you what you need. Please confirm.

**Comment by smpallen99** [comment]
Feature is included in hex version 0.5.1
