### ISSUE TITLE
Registration form labels aren't linked to input fields

### ISSUE THREAD

**Issue by zedtux** [smpallen99/coherence#315]
I'm completely new to Elixir/Phoenix and coherence, and I have created a new phoenix project and added coherence and all is working fine.

Now I'm writing tests and I need to login before to do whatever else, but my test is failing stating that the label `for` isn't matching any fields on the page.

Have a closer look at the source code of the page I found out that the label `for` contains `registration_Name` while the input field as its `id` attribute to `registration_name`.

I think the issue comes from the `required_label` function which should receive and pass the field to [the `label` call](https://github.com/smpallen99/coherence/blob/956b6b7412951f452386cc5861d5cc5c7896be04/priv/templates/coh.install/views/coherence/coherence_view_helpers.ex#L184).

I have updated the `form.eex` file replacing the `required_label` with:

```elixir
    <%= label f, :name, class: "control-label" do %>
      <%= dgettext("coherence", "Name") %>
    <% end %>
```

then the label is now well connected to the field.

**Comment by smpallen99** [comment]
Thanks for reporting. Would be a nice PR for someone new to the project.

**Comment by zedtux** [comment]
As I’m really new to the Elixir world, I wasn’t sure enough to open a PR, but now I have you confirmation, I’lol open it. Thank you.

**Comment by sivagollapalli** [comment]
I am really new to elixir world. My guess is by removing `humanize` function from https://github.com/smpallen99/coherence/blob/956b6b7412951f452386cc5861d5cc5c7896be04/priv/templates/coh.install/views/coherence/coherence_view_helpers.ex#L186 would solve this problem I think?

**Comment by marnen** [comment]
What seems to work for me is to change `dgettext("coherence", "Password")` to `dgettext("coherence", "password")`. The `humanize` function still capitalizes the display text, but makes the actual `for` attribute lowercase to match the actual field.

**Comment by zedtux** [comment]
Thank you @smpallen99
