### ISSUE TITLE
Not localized links

### ISSUE THREAD

**Issue by almays** [smpallen99/coherence#322]
Hello.
I'm using `coherence_links` from `coherence_view_helpers.ex` in my navbar.

The thing is that the texts in the links doesn't get localized to other locale. I cannot understand from the code, why it doesn't. All other things get translated. My own stuff and coherence strings (like in signup form). But these buttons "Need An Account? | Sign In" remain English.

https://github.com/smpallen99/coherence/blob/1f58ba520f6f7dae9e37d79ec0ebc0ca1b06d5b4/priv/templates/coh.install/views/coherence/coherence_view_helpers.ex#L93

**Comment by smpallen99** [comment]
The text is not localized because `dgettext/2` is being called at compile time and assigned to module variables. The gettext macro's need to be called at runtime. I need to change these to functions instead of modules attributes.
