### ISSUE TITLE
0.5.1 Release Date?

### ISSUE THREAD

**Issue by daneb** [smpallen99/coherence#331]
Good day

Thanks firstly, for a great library ;)
I see 0.5.1 has been released for some time, but wondering when we may see the package published to hex.pm?

Thanks for your time
Dane

**Comment by 51stpage** [comment]
I was going to ask about this too.  The Confirmation_path() fix somewhere after 0.5 has been very helpful but it weirds me out to use a raw git repo for my projects.  I'd much prefer to use a 0.5.1 release with just that fix in it.

Appreciate the project a great deal.  Thank you for making it available.

**Comment by danschultzer** [comment]
@smpallen99 any update on this? Let me know if you would like any help to prepare the next release.

**Comment by seanculver** [comment]
@smpallen99 Definitely appreciate the work you've put into this project. I also know the pressure in maintaining such a large, and well used project. I can see community members want to contribute to this projects success. Sometimes, it can be even overwhelming trying to come up with how someone else can help you. Would you need help with this aspect?  Also, no blame, we all live busy lives. Cheers!

**Comment by smpallen99** [comment]
Released 0.5.1 this evening
