### ISSUE TITLE
all compilation failing with gettext error

### ISSUE THREAD

**Issue by beta-phenylethylamine** [smpallen99/coherence#337]
I'm fairly new to the elixir/phoenix ecosystem so I'm fairly stumped by this. I can only imagine there's something I'm missing since no one else has mentioned this, but I can't figure out what it'd be

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 20)
```

```
== Compilation error in file lib/fontina_web/coherence_messages.ex ==
** (ArgumentError) *gettext macros expect translation keys (msgid and msgid_plural) and
domains to expand to strings at compile-time, but the given msgid
doesn't.

Dynamic translations should be avoided as they limit gettext's
ability to extract translations from your source code. If you are
sure you need dynamic lookup, you can use the functions in the Gettext
module:

    string = "hello world"
    Gettext.gettext(FontinaWeb.Gettext, string)

    (gettext) lib/gettext/compiler.ex:231: Gettext.Compiler.expand_to_binary/4
    expanding macro: FontinaWeb.Gettext.dgettext_noop/2
    lib/fontina_web/coherence_messages.ex:75: FontinaWeb.Coherence.Messages.you_are_using_an_invalid_security_token/0
    expanding macro: FontinaWeb.Gettext.dgettext/2
    lib/fontina_web/coherence_messages.ex:75: FontinaWeb.Coherence.Messages.you_are_using_an_invalid_security_token/0
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by beta-phenylethylamine** [comment]
It looks like smpallen99/ex_admin#425 is talking about the same issue. For now I'll just downgrade, but keep the issue open.

**Comment by beta-phenylethylamine** [comment]
Ah, got it. it was the string concatenation on `you_are_using_an_invalid_security_token`

Removing it solved the issue. I'll write up a pull request I suppose.

**Comment by beta-phenylethylamine** [comment]
Closing. Looks like it's already fixed on master, just not on hex.

**Comment by AlmogRnD** [comment]
I'm running into the same issue, I just installed coherence so is this fixed yet?

**Comment by beta-phenylethylamine** [comment]
It's fixed in master, but that hasn't made it to hex yet. You can get the hex version to compile locally by going into your project and getting rid of the string concatenation in `coherence_messages.ex` for `you_are_using_an_invalid_security_token` (just combine the two strings into one)

**Comment by AlmogRnD** [comment]
@beta-phenylethylamine thanks solved
