### ISSUE TITLE
Does coherence support social login buttons? 

### ISSUE THREAD

**Issue by AlmogRnD** [smpallen99/coherence#338]
I wanted to know if coherence supports social login buttons like Facebook, Github and Google Apps? 

Thanks,
Almog

**Comment by OvermindDL1** [comment]
Aren't those just normal OAuth and other such variant logins?  What makes them social?

**Comment by AlmogRnD** [comment]
Yes that is correct, wanted to see if there was supported UI and an easy way to set this up
