### ISSUE TITLE
Invitation link page displays sign in form instead registration form

### ISSUE THREAD

**Issue by shhavel** [smpallen99/coherence#35]
New user clicks on invitation link from email, e.g.:
http://localhost:4000/invitations/d5cF52gPkNMyMIa60covote5axri3qrLODtZ9lc8dk9BbhL1/edit

This displays sign in form (but new user have no account yet):

![sign_in_form](https://cloud.githubusercontent.com/assets/1169424/17362490/f571f8f4-597d-11e6-8fca-a51b9174c2e3.png)

instead of registration form which displayed only if user is already authenticated:

![registration_form](https://cloud.githubusercontent.com/assets/1169424/17362494/f8777308-597d-11e6-8e6d-c2ee1adaeccd.png)

Is there something I am missing?
Maybe some of invitation routes should be public (do not require login)
or user should be authorized by the token from the URL? 
Thanks

**Comment by smpallen99** [comment]
Your right, this is an issue. I'll get it fixed today.

**Comment by shhavel** [comment]
Thanks!
