### ISSUE TITLE
registration_create redirect not working 

### ISSUE THREAD

**Issue by AlmogRnD** [smpallen99/coherence#352]
I set up the following redirect which should be triggered after a user creates their account 

# redirect the user to the dashboard page after registering
  def registration_create(conn, _), do: redirect(conn, to: "/dashboard")

As you can see this does not work 

![issue-1](https://user-images.githubusercontent.com/169507/40416331-581b3986-5ec0-11e8-826d-590c56de6012.gif)

**Comment by smpallen99** [comment]
@jung-hunsoo is correct. Assuming from lack of reply that this issue has been resolved. Closing.
