### ISSUE TITLE
Generated controllers out of sync

### ISSUE THREAD

**Issue by DanielDent** [smpallen99/coherence#362]
The controllers generated by the `mix coh.gen.controllers` mix task appear to be out of date with the controllers which are used by default. There have been a number of minor updates/bugfixes (e.g. Ecto.DateTime.utc() vs NaiveDateTime.utc_now()) which have not made their way into the auto-generated controllers.

**Comment by smpallen99** [comment]
I just regenerated the controllers in my last couple of pushed. This should be resolved.
