### ISSUE TITLE
from 0.2 to 0.3

### ISSUE THREAD

**Issue by nordbit** [smpallen99/coherence#37]
Please check your upgrade instruction, installation script and configuration in readme.

Installation script generate file "web/controllers/coherence/redirects.ex" with content:
`import CoherenceDemo.Router.Helpers`

In readme is still:

```
def deps do
  [{:coherence, "~> 0.2"}]
end
```

but configuration  references to version 0.3 (with new ":protected" feature)

And installation script still display on console old configuration example (v0.2)

I mentioned no new packages on hex.pm?

**Comment by smpallen99** [comment]
I'll review. I'm still working an a couple things in master before I publish to hex.
