### ISSUE TITLE
can't be blank

### ISSUE THREAD

**Issue by mattgaudio** [smpallen99/coherence#371]
Processing with Coherence.RegistrationController.create/2
  Parameters: %{"_csrf_token" => "Iho9FAlTES1jCwsZXVpyVxReRS4GAAAAFIUW15pN5FhvnbD5y13g7Q==", "_utf8" => "✓", "registration" => %{"email" => "quickhat22@Gmail.com", "name" => "quickhat22", "password" => "[FILTERED]", "password_confirmation" => "[FILTERED]"}}

registration processed but rendered error with can't be blank alerts above the email, password and password confirmation fields.

**Comment by pradosh987** [comment]
I am having same problem. New version 0.5.1 kind of has breaking changes thats not documented anywhere. For ex. whats `  registration_permitted_attributes` , in registration controller '`Controller.changeset` always return empty struct.

**Comment by smpallen99** [comment]
I'm sorry for the inconvenience. Yes, 0.5.1 introduced the permitted_attributes feature, requiring this configuration. This is a huge security improvement. I'm thinking of adding defaults so upgraded applications without the config will have a sensible default.

**Comment by openmosix** [comment]
@smpallen99 make sense! I think just mentioning in the doc (the new setting) should suffice for now. And btw - thanks a lot for running this project 👍

**Comment by pradosh987** [comment]
@smpallen99 Also please consider adding changeling, even one liner would be enough. Anyways great job with this library.
