### ISSUE TITLE
reset_password_token isn't filled again

### ISSUE THREAD

**Issue by manuel-rubio** [smpallen99/coherence#387]
Everything works fine but there are a specific case:

1.- User requires a link to change the password
2.- User receives the link a open it in the browser
3.- User put different passwords and that gives him an error
4.- Try again and then "token is invalid"

The problem in the step 3 is the hidden field isn't populated the second time. I was checking the changeset and everything and I cannot find the error, anyone can shed a light on that? Thanks.

**Comment by smpallen99** [comment]
Merged PR
