### ISSUE TITLE
Install option to remove an option

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/coherence#4]
Add an installer option to remove an option from a project that has already installed coherence.

**Comment by gwincr11** [comment]
I am curious about this, I installed but it setup Registerable. Is there a way to configure coherences modules other than at install time?

**Comment by smpallen99** [comment]
All the installer does, depending on the options you select, is generate files for views, models, templates, email, and controllers in coherence directories in your project. It also sets up coherence config in your config/config.exs file. Run time stuff is handles by the `opts` section in the `:coherence` config entry. If you want to remove something manually, just change config.exs and delete the relevant templates, views, etc.

Perhaps I should should have a default to yes option to confirm that installation options before running the generators.
