### ISSUE TITLE
phoenix_timex dependency conflict with Timex 3.0

### ISSUE THREAD

**Issue by devshane** [smpallen99/coherence#40]
Hello, I'm using Timex 3.0 in my project and I think there are conflicts with the `phoenix_timex` lib's dependencies that prevent me from installing coherence.

The functionality in `phoenix_timex` is pretty limited -- is it worth implementing directly?

```
Running dependency resolution

Failed to use "phoenix_html" (version 2.6.1) because
  coherence (version 0.2.0) requires ~> 2.4
  phoenix_ecto (version 3.0.0) requires ~> 2.6
  phoenix_swoosh (version 0.1.3) requires ~> 2.2
  phoenix_timex (version 1.0.0) requires ~> 2.5.1
  Locked to 2.6.1 in your mix.lock


Failed to use "timex" because
  phoenix_timex (version 1.0.1) requires ~> 2.1
  Locked to 3.0.1 in your mix.lock
```

**Comment by smpallen99** [comment]
I’ve alway been able to get around these errors by adding the dependency to my project with override: true.

For example:

```
	{:phoenix_html, “~> 2.6”, override: true}
```

**Comment by devshane** [comment]
So after a little more digging and a PR over on `phoenix_timex`, I've learned Elixir 1.3 implements Phoenix.HTML.Safe with the new Calendar types. Since coherence requires ~> 1.3, I think this renders the `phoenix_timex` package obsolete if you bump the version of Timex.

Closed PR: https://github.com/Paradem/phoenix_timex/pull/4

A fork with Timex 3 support: https://github.com/devshane/coherence/tree/timex3

I can submit a PR if you're interested. Thanks for having a look!

**Comment by joshuataylor** [comment]
Updating to timex 3.0 would be great.

**Comment by manukall** [comment]
i would also greatly appreciate this. @devshane i looked at your fork and it seems to be mergable. would you still want to submit a PR? is there anything in the way of this?

**Comment by devshane** [comment]
@manukall @joshuataylor apologies for not doing this sooner... I submitted a PR https://github.com/smpallen99/coherence/pull/111

**Comment by manukall** [comment]
@devshane no apologies needed. thanks a lot!

**Comment by joshuataylor** [comment]
Fantastic fix, thanks for doing this!

And very quick merge :)
