### ISSUE TITLE
phoenix 1.4

### ISSUE THREAD

**Issue by MattGaud2425** [smpallen99/coherence#410]
Failed to use "ecto" (versions 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.2.10, 2.2.11) because
  deps/coherence/mix.exs requires ~> 2.0
  ecto_sql (version 3.0.3) requires ~> 3.0.4

**Comment by mattgaudio** [comment]
Compiling 49 files (.ex)

== Compilation error in file lib/mix/tasks/coh.clean.ex ==
** (CompileError) lib/mix/tasks/coh.clean.ex:309: undefined function migrations_path/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
could not compile dependency :coherence, "mix compile" failed. You can recompile this dependency with "mix deps.compile coherence", update it with "mix deps.update coherence" or clean it with "mix deps.clean coherence"

**Comment by JesperWe** [comment]
This is well known and there is already PR #400 which passes all tests but no one is merging it unfortunately...

**Comment by thalesmiguel** [comment]
@mattgaudio As mentioned by @JesperWe, the [PR that fix this](https://github.com/smpallen99/coherence/pull/400) is ready but still not merged.
For now, you could use something like `[{:coherence, git: "https://github.com/appprova/coherence.git", branch: "upgrade-to-phoenix-1.4"}]` on your `mix.exs` file. This is the repository used to open the PR mentioned above.

**Comment by MattGaud2425** [comment]
Issue is outdated and fixed.
