### ISSUE TITLE
Use a table for trackable

### ISSUE THREAD

**Issue by obsidienne** [smpallen99/coherence#45]
Hi, 

I think we should create a data table storing every login attempts (succeed and failed) and logouts.

Will you accept PR for this ?

Thanks

**Comment by smpallen99** [comment]
Yes, I'll accept a RP for this provided its an install option. I'm thinking `--trackable-table` option. I'm just wondering if we should keep the same trackable options in the user model for this feature, or store them in the table instead?

**Comment by obsidienne** [comment]
```
add :sign_in_count, :integer, default: 0  # how many times the user has logged in
add :current_sign_in_at, :datetime        # the current login timestamp
add :last_sign_in_at, :datetime           # the timestamp of the previous login
add :current_sign_in_ip, :string          # the current login IP adddress
add :last_sign_in_ip, :string             # the IP address of the previous login
```

I think we can move the trackable options too. But do we provide helper functions to get those informations ?

**Comment by smpallen99** [comment]
I'm on the fence about moving the trackable options, but leaning towards keeping them in the user model. One of the reasons for keeping them in the user model is that it works better with whatwasit when storing the user model as a map. 

So, I would prefer to keep them in the user model. So this new feature will just add a new table and update the table on every login.

**Comment by obsidienne** [comment]
Then maybe only keep in the user model the `sign_in_count`, `current_sign_in_at` and `current_sign_in_ip` with the `--trackable-table` option ? 


_I don't like devise & devise_invitable with the 'everything in the model'._

**Comment by smpallen99** [comment]
I can see your point, but its giving me some heartburn. Some of my concerns:
* different user schema depending on `--trackable-table`
* if I add `--trackable-table` later on, then either they create a migration to remove the fields from the user model, or we stop updating them on new logins

**Comment by obsidienne** [comment]
My goal with this bug was:

1. store in a table every log in, failed log in, and log out with date, ip, etc
2. remove unecessary fields according to 1

We could say:

- there is no specific `--trackable-table` option
- coherence creates a `trackable` table where every events on auth are tracked
 - succeed log in
 - failed log in
 - log out
 - locked account
 - unlocked account
 - ...

we keep `sign_in_count`, `current_sign_in_at` and `current_sign_in_ip` in the user model for whatwasit.

I think it's an interesting option

**Comment by smpallen99** [comment]
Lets do this. Keep `--trackable` the same as it is today. Make `--trackable-table` work without requiring `--trackable`. This allows backwards compatibility and an option that does not pollute the user model. In the future, we may decide to deprecate `--trackable`.

**Comment by mayppong** [comment]
I'm very interested in this feature. I'm currently working on a project where audit-ability is very important. I would love to see this trackable table to also track reset password request as well. Is this too late to add as an input. I'm happy to contribute to the feature for sure.

**Comment by obsidienne** [comment]
I have not started yet. Sure, reset password requests will be logged
