### ISSUE TITLE
Configurable changeset functions

### ISSUE THREAD

**Issue by rzane** [smpallen99/coherence#46]
On the registration form of my app, I'm attempting to create a record that is associated with my user model using `cast_assoc`:

```elixir
# user.ex
def changeset(model, params \\ %{}) do
  model
  |> cast(params, @required_fields ++ coherence_fields)
  |> cast_assoc(:thing, required: true)
  |> unique_constraint(:email)
  |> validate_coherence(params)
end

# registration/new.html.eex
<%= inputs_for f, :thing, fn t -> %>
  <%= text_input t, :name %>  
<% end %>
```

This works fine for registration, the user is created and so is the associated record. Unfortunately, when I attempt to login, I get:

```
Request: POST /sessions
** (exit) an exception was raised:
    ** (RuntimeError) attempting to cast or change association `thing` from `MyApp.User` that was not loaded. Please preload your associations before manipulating them through changesets
```

If changesets were configurable, it would give more control to the developer. But, perhaps there is a better way to handle this that I'm not aware of.

**Comment by smpallen99** [comment]
I believe this is an issue with the trackable option. Presuming you have trackable enabled, the issue is due to the association not be preloaded when the trackable fields are updated. 

I need to think about an extensible solution for this issue. However, you can fix this for your project by generating the controllers and modifying the session_controller by editing the create function and adding a preload:

```elixir
user = Config.repo.one(from u in user_schema, where: field(u, ^login_field) == ^login)
|> Config.repo.preload([:thing])
```

You should also edit the delete function like this:

```elixir
user = conn.assigns[Config.assigns_key]
|> Config.repo.preload([:thing])
```

**Comment by rzane** [comment]
In this case, I don't really even want to preload that association. I'd rather specify a different changeset that won't require the association to be preloaded, so that's what I'll do.

**Comment by smpallen99** [comment]
Ok, I get it. So you want a configurable trackable changeset? That should be pretty simple to do. We can check for a configuration entry and if present, use it instead of the default changeset.

**Comment by rzane** [comment]
Actually, in my case, I'd like a configurable registration changeset. I only want to invoke `cast_assoc(:thing)` when the user is registering.

**Comment by smpallen99** [comment]
This has been a good discussion. I'm going to make all changesets configurable.

**Comment by rzane** [comment]
Thanks, this is perfect!
