### ISSUE TITLE
Suggestion for `pipe_through` example in README

### ISSUE THREAD

**Issue by mayppong** [smpallen99/coherence#51]
The `:browser` and `:protected` pipe are almost identical. It's actually possible to define multiple pipes in the router scope to be pipe through.

```
pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
end

pipeline :protected do
    plug Coherence.Authentication.Session, protected: true
end

scope "/", MyProject do
    pipe_through [:browser, :protected]

    # add protected resources below
    resources "/privates", MyProject.PrivateController
end
```

This makes a cleaner example. I'm happy to put up a PR if you agree.

**Comment by smpallen99** [comment]
There is an issue with the above proposal. Without the `plug Coherence.Authentication.Session` call in the :browser pipeline, any checks for current_user for non protected pages will not find current_user. For example, if you have `coherence_links(@conn, :layout)` call in the layout template, it will issue a `login` link for pages that are not protected.

You could add `plug Coherence.Authentication.Session` to the :browser pipeline, but then you will be calling the plug twice for each protected page. This will not break anything, but is not optimal.

Given this, I prefer to leave things alone.

**Comment by OvermindDL1** [comment]
Could have both a `:protected` and a `:nonprotected` routes or so.

**Comment by smpallen99** [comment]
We already have it with `coherence_routes/0`. Here is how it works:
```
coherence_routes                       # unprotected
coherence_routes :protected    # protected routes requiring login
coherence_routes :all                 # all routes
```
