### ISSUE TITLE
Allow unconfirmed access for a grace period?

### ISSUE THREAD

**Issue by jaimeiniesta** [smpallen99/coherence#54]
When using `confirmable`, is there a way to define a grace period during which the user is allowed to log in even if the email hasn't yet been confirmed?

[Devise does this](https://github.com/plataformatec/devise/wiki/How-To:-Add-:confirmable-to-Users#allowing-unconfirmed-access), and I think it's a nice feature to have, so user onboarding is smoother.

Also, it would be great if a user automatically was signed in after a successful sign up.

**Comment by smpallen99** [comment]
Supported
