### ISSUE TITLE
"Using Ecto.Model is deprecated, please use Ecto.Schema instead"

### ISSUE THREAD

**Issue by scouten** [smpallen99/coherence#58]
After doing `mix coherence.install`, I get this warning in my app.

**Comment by shhavel** [comment]
@scouten You can try to find `use Ecto.Model` is `*.ex` files (probably in `web/web.ex`) and replace it with `use Ecto.Schema`

Thanks

**Comment by smpallen99** [comment]
I can't find any in the coherence code, only a couple references in some of the depenencies
