### ISSUE TITLE
Add a README section for testing

### ISSUE THREAD

**Issue by obsidienne** [smpallen99/coherence#59]
Hi,

I'm new to phoenix, elixir and coherence. I don't know how to bypass coherence in tests to tests my controllers. 

In the scaffold done by phoenix, i have `conn = get conn, user_path(conn, :index)`, but the test fails because I have protected those url with coherence.

Any help ?

thanks

**Comment by shhavel** [comment]
Hi, 
You can create a user and assign variable `:current_user` before `get`

```elixir
user = Repo.insert! %User{email: "test@example.com"}
conn = assign conn, :current_user, user
conn = get conn, user_path(conn, :index)
```
Hope this helps. Thanks

**Comment by egeersoz** [comment]
Adding to what @shhavel, this is what I have in my tests for protected routes and it works great:

```
defmodule MyApp.PostControllerTest do
    use MyApp.ConnCase

    setup %{conn: conn} do
        user_changeset = User.changeset(%User{}, %{name: "test", email: "test@example.com", password: "test", password_confirmation: "test"})
        user = Repo.insert! user_changeset
        {:ok, conn: assign(conn, :current_user, user), user: user}
    end

    # your tests here

end
```

When you do that, any time you use the `conn` map in your tests, it will satisfy Coherence's login requirement. For example:

```
test "lists all entries on index", %{conn: conn} do
    conn = get conn, post_path(conn, :index)
    assert html_response(conn, 200) =~ "Listing posts"
end
```

**Comment by smpallen99** [comment]
I'm starting to use the wiki instead of bloating the readme. I've added the following entry.
https://github.com/smpallen99/coherence/wiki/Testing-with-Coherence
