### ISSUE TITLE
Auto log user in after confirmation click

### ISSUE THREAD

**Issue by jeffdeville** [smpallen99/coherence#61]
I'll try and put this together in a PR when I get some time. Is this the sort of thing that anyone would want there to be an option for? It seems like performing the login would make the most sense.

**Comment by egeersoz** [comment]
There should be config options for logging in the user automatically after they register. If `:confirmable` is turned on, it should automatically log them in when they confirm.

**Comment by seanculver** [comment]
Is there a PR related to this that has been merged? Cheers!

**Comment by smpallen99** [comment]
@seanculver set `: allow_unconfirmed_access_for` config to some number of days.

**Comment by seanculver** [comment]
@smpallen99 Thank you!
