### ISSUE TITLE
coherence/redirects.ex has unused import warning

### ISSUE THREAD

**Issue by scouten** [smpallen99/coherence#62]
```
warning: unused import Main.Router.Helpers
  web/controllers/coherence/redirects.ex:45

Compilation failed due to warnings while using the --warnings-as-errors option
```

**Comment by shhavel** [comment]
I had the same issue, have resolved it by removing/commenting line https://github.com/smpallen99/coherence/blob/2cd32425fe93267ec0b9bc5cdb8b0f869813e78d/priv/templates/coherence.install/controllers/coherence/redirects.ex#L45 

@smpallen99 Maybe this line should  be commented in template?

**Comment by scouten** [comment]
Yes, I commented it out, too. Just suggesting this as an improvement to Coherence. 😄
