### ISSUE TITLE
Add Dialyzer typespecs

### ISSUE THREAD

**Issue by gwbrown** [smpallen99/coherence#67]
In order to assist in refactoring and debugging efforts, as well as providing additional documentation, it would be good to add Dialyzer typespecs to this project.

I'm willing to take this on, unless I get told this will be rejected I'll start working on this shortly.

**Comment by smpallen99** [comment]
I would accept a PR for this. Good idea!

**Comment by smpallen99** [comment]
@gwbrown have you made any progress on this. I took a shot at it the other night, forgetting that you were going to take it on. I still need to debug a number of dialyzer errors/warnings. I can push a branch if your interested in looking at it.
