### ISSUE TITLE
redirect_logged_in should redirect to session_create page instead of the logged_out_url

### ISSUE THREAD

**Issue by ben-ic** [smpallen99/coherence#69]
If the logged_out_url is configured as the registration page or login page the web app will go into an infinite loop if a user attempts to load one of those pages while being logged in.  It would be better if it redirected to the session_create page.

A temporary fix is to create your own custom coherence controllers and remove the :redirect_logged_in plug.

**Comment by smpallen99** [comment]
Added new Config.logged_in_url that redirect_logged_in uses. This should avoid redirect loop.
