### ISSUE TITLE
conn.assings[:current_user] not reloaded

### ISSUE THREAD

**Issue by AdrianRibao** [smpallen99/coherence#81]
I'm using the :current_user from conn.assigns to check if the user has a flag is_admin set.

If I change the flag in the database, the information in conn.assigns[:current_user] is not changing. It only does when restarting the server.

**Comment by smpallen99** [comment]
This update provides support for updating the credential store in the registration update action. Additionally, I added some notes in the READ.ME file for manually updating the credential store `update_login` from you own controllers.
