### ISSUE TITLE
User id seems to be unnecessarily exposed in registration routes

### ISSUE THREAD

**Issue by egeersoz** [smpallen99/coherence#90]
Coherence.Router defines the protected registration routes as such:

```
get "/registrations/:id", Coherence.RegistrationController, :show
put "/registrations/:id", Coherence.RegistrationController, :update
patch "/registrations/:id", Coherence.RegistrationController, :update
get "/registrations/:id/edit", Coherence.RegistrationController, :edit
```

However, the RegistrationController functions get the user's id from `conn`:

```
  def show(conn, _) do
    user = Coherence.current_user(conn)
    render(conn, "show.html", user: user)
  end
```

If I redefine the routes like this, they still work:

```
get "/account", Coherence.RegistrationController, :show
```

So having the user id as an explicit, visible parameter doesn't seem necessary.

**Comment by smpallen99** [comment]
You right. I fixed this for the session routes. Need to do the same for registrations, I guess.
