### ISSUE TITLE
Redirects module doesn't seem to work if controllers are generated during installation

### ISSUE THREAD

**Issue by egeersoz** [smpallen99/coherence#93]
I first installed Coherence using the default settings, which does not install controllers. It just generates Coherence.Redirect, which I started using without issues.

Then I decided to run the installer again, and this time supplied the `--controllers` option. I chose not to overwrite any of the existing files (as I had already customized some of them). It generated the controllers. I then added `MyApp` to my route scopes as instructed in the Readme, e.g.:

```
scope "/", MyApp do
    ...
    coherence_routes
end
```

At this point, the Redirect module stopped working.

I verified the problem by changing my routes back to the way they were (by removing `MyApp` above), so that they would use the controllers inside `deps/coherence/web`. Redirects started working again.

Is there something special that needs to be done if controllers are added after the fact and none of the existing files are overwritten?

**Comment by smpallen99** [comment]
Try `mix deps.compile coherence`. The only thing I can think of is that  after you change the router scope it may not be picked up until recompile. 

The redirects  code is not name spaced, so it should not matter if you change to custom controllers. Let me know if that helps.

Steve

**Comment by egeersoz** [comment]
It is actually picked up after changing the router scope. I verified it by using `Logger.debug` statements inside the actions of the RegistrationController. So that's not it.

For now, I deleted the created controllers and went back to using the ones in `deps/coherence/web`. Unfortunately I don't have time to debug this particular issue. I'll go ahead and close it.
