### ISSUE TITLE
[SOLVED] Syntax error before: eol

### ISSUE THREAD

**Issue by alzearafat** [smpallen99/coherence#95]
Hi there

I created simple CRUD app called "Idea", and trying to implement Coherence to it. Everything is going smooth, except I getting stuck when following this order : 

----------------
For example, lets say you want to show a list of products for everyone visiting the site, but only want authenticated users to be able to create, update, and delete products. You could do the following:

...
```
defmodule MyProject.ProductController do
  use MyProject.Web, :controller
  alias MyProject.Product

  Coherence.Authentication.Session, [protected: true] when action != :index
```
----------------

Apparently, this syntax `Coherence.Authentication.Session, [protected: true] when action != :index`, create this error : 

```
$ mix phoenix.server

== Compilation error on file web/controllers/idea_controller.ex ==
** (SyntaxError) web/controllers/idea_controller.ex:5: syntax error before: eol
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
I think I missplace the code, but I just following the readme.

Any help would be greatly appreciated :) 
Thank you

**Comment by kimquy** [comment]
@alzearafat I think the documentation is missing `plug`

Can you try again with this

```ruby
plug Coherence.Authentication.Session, [protected: true] when action != :index
```

Then I think it should work as expected.

**Comment by alzearafat** [comment]
@kimquy 

Yes, thank you :D 
It's solved!
